'use client'

import { createClient } from '@/lib/supabase/client'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import Link from 'next/link'

export default function HomePage() {
  const router = useRouter()
  const supabase = createClient()
  const [user, setUser] = useState(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const checkUser = async () => {
      const {
        data: { user },
      } = await supabase.auth.getUser()
      setUser(user)
      setLoading(false)
    }

    checkUser()
  }, [supabase])

  if (loading) {
    return null
  }

  if (user) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-background to-secondary">
        {/* Header */}
        <header className="border-b bg-background/50 backdrop-blur-sm">
          <div className="max-w-6xl mx-auto px-4 md:px-8 py-4 flex justify-between items-center">
            <h1 className="text-2xl font-bold">CardAI</h1>
            <div className="flex gap-3">
              <Link href="/dashboard">
                <Button>Dashboard</Button>
              </Link>
              <Button
                variant="outline"
                onClick={async () => {
                  await supabase.auth.signOut()
                  router.push('/')
                }}
              >
                Logout
              </Button>
            </div>
          </div>
        </header>

        {/* Welcome Section */}
        <div className="max-w-6xl mx-auto px-4 md:px-8 py-16 text-center">
          <h2 className="text-4xl font-bold mb-4">Welcome Back!</h2>
          <p className="text-xl text-muted-foreground mb-8">
            Ready to create another amazing card?
          </p>
          <Link href="/create">
            <Button size="lg">Create New Card</Button>
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-background to-secondary">
      {/* Header */}
      <header className="border-b bg-background/50 backdrop-blur-sm">
        <div className="max-w-6xl mx-auto px-4 md:px-8 py-4 flex justify-between items-center">
          <h1 className="text-2xl font-bold">CardAI</h1>
          <div className="flex gap-3">
            <Link href="/auth/login">
              <Button variant="outline">Login</Button>
            </Link>
            <Link href="/auth/sign-up">
              <Button>Sign Up</Button>
            </Link>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <div className="max-w-6xl mx-auto px-4 md:px-8 py-16 md:py-24 text-center">
        <h2 className="text-4xl md:text-5xl font-bold mb-4 text-balance">
          Create Beautiful Greeting Cards with AI
        </h2>
        <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto text-balance">
          Generate personalized greeting cards with AI-powered text and images. Invite friends and
          family to add messages before sending to the recipient.
        </p>

        <div className="flex flex-col sm:flex-row gap-4 justify-center mb-16">
          <Link href="/auth/sign-up">
            <Button size="lg">Get Started Free</Button>
          </Link>
          <Link href="/auth/login">
            <Button size="lg" variant="outline">
              I Already Have an Account
            </Button>
          </Link>
        </div>

        {/* Features Grid */}
        <div className="grid md:grid-cols-3 gap-8 py-16">
          <Card className="p-8">
            <div className="text-4xl mb-4">🎨</div>
            <h3 className="text-xl font-bold mb-3">AI-Generated Images</h3>
            <p className="text-muted-foreground">
              Beautiful, unique card images generated by AI for every occasion
            </p>
          </Card>

          <Card className="p-8">
            <div className="text-4xl mb-4">✍️</div>
            <h3 className="text-xl font-bold mb-3">Personalized Copy</h3>
            <p className="text-muted-foreground">
              Smart AI generates heartfelt, customized messages for any card type
            </p>
          </Card>

          <Card className="p-8">
            <div className="text-4xl mb-4">👥</div>
            <h3 className="text-xl font-bold mb-3">Group Contributions</h3>
            <p className="text-muted-foreground">
              Share cards with friends and family to add their own messages
            </p>
          </Card>

          <Card className="p-8">
            <div className="text-4xl mb-4">🎁</div>
            <h3 className="text-xl font-bold mb-3">Multiple Card Types</h3>
            <p className="text-muted-foreground">
              Birthday, thank you, congratulations, holiday, and custom cards
            </p>
          </Card>

          <Card className="p-8">
            <div className="text-4xl mb-4">📧</div>
            <h3 className="text-xl font-bold mb-3">Easy Sharing</h3>
            <p className="text-muted-foreground">
              Share cards via link or email to any recipient
            </p>
          </Card>

          <Card className="p-8">
            <div className="text-4xl mb-4">🔧</div>
            <h3 className="text-xl font-bold mb-3">Fully Customizable</h3>
            <p className="text-muted-foreground">
              Edit generated text and regenerate images to get exactly what you want
            </p>
          </Card>
        </div>
      </div>

      {/* CTA Section */}
      <div className="bg-background/50 border-t">
        <div className="max-w-6xl mx-auto px-4 md:px-8 py-16 text-center">
          <h3 className="text-3xl font-bold mb-4">Ready to Create Your First Card?</h3>
          <p className="text-lg text-muted-foreground mb-8">
            Join thousands of people creating meaningful greetings with AI
          </p>
          <Link href="/auth/sign-up">
            <Button size="lg">Start Creating Now</Button>
          </Link>
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t bg-background/50">
        <div className="max-w-6xl mx-auto px-4 md:px-8 py-8 text-center text-sm text-muted-foreground">
          <p>CardAI • Create beautiful greeting cards with AI</p>
        </div>
      </footer>
    </div>
  )
}
