"use client"

import { createClient } from "@/lib/supabase/client"
import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Logo } from "@/components/logo"

const OCCASIONS = [
  { id: "birthday", label: "Birthday", hue: 18 },
  { id: "thank_you", label: "Thank you", hue: 40 },
  { id: "congrats", label: "Congrats", hue: 70 },
  { id: "holiday", label: "Holiday", hue: 150 },
  { id: "sympathy", label: "Sympathy", hue: 310 },
  { id: "custom", label: "Custom", hue: 230 },
]

const FEATURES = [
  {
    n: "01",
    title: "One link, everyone signs",
    desc: "Each person places their note anywhere on the page. Drag, resize, rotate, add a GIF.",
  },
  {
    n: "02",
    title: "AI drafts first, you edit",
    desc: "Regenerate any line, any cover, any time. The AI has a light touch — never saccharine.",
  },
  {
    n: "03",
    title: "Private until send",
    desc: "No one sees the card until you decide it's full. Then it arrives, beautifully, in one email.",
  },
]

export default function HomePage() {
  const router = useRouter()
  const supabase = createClient()
  const [loading, setLoading] = useState(true)
  const [activeOccasion, setActiveOccasion] = useState("birthday")

  useEffect(() => {
    const checkUser = async () => {
      const {
        data: { user },
      } = await supabase.auth.getUser()

      if (user) {
        router.replace("/dashboard")
        return
      }

      setLoading(false)
    }

    checkUser()
  }, [router, supabase])

  if (loading) {
    return null
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-50 border-b border-border bg-background/95 backdrop-blur-sm">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-[18px]">
          <div className="flex items-center gap-8">
            <Logo />
            <nav className="hidden items-center gap-6 text-sm text-muted-foreground md:flex">
              <Link
                href="/create"
                className="transition-colors hover:text-foreground"
              >
                Browse
              </Link>
              <span className="cursor-default transition-colors hover:text-foreground">
                How it works
              </span>
              <span className="cursor-default transition-colors hover:text-foreground">
                For teams
              </span>
            </nav>
          </div>
          <div className="flex items-center gap-3">
            <Link
              href="/auth/login"
              className="text-sm text-muted-foreground transition-colors hover:text-foreground"
            >
              Sign in
            </Link>
            <Link href="/create">
              <Button variant="brand" size="sm">
                Start a card
              </Button>
            </Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="mx-auto grid max-w-7xl grid-cols-1 items-center gap-12 px-6 py-20 lg:grid-cols-[1.15fr_1fr] lg:gap-16 lg:py-20">
        <div>
          <div className="inline-flex items-center gap-2 rounded-full border border-border bg-card px-3 py-1.5 text-sm text-muted-foreground">
            <span className="h-1.5 w-1.5 rounded-full bg-brand" />
            New — image regeneration with reference photos
          </div>
          <h1 className="mt-5 text-5xl leading-[0.95] font-semibold tracking-[-0.04em] text-balance md:text-6xl lg:text-[80px] xl:text-[96px]">
            Greeting cards,
            <br />
            <span className="text-muted-foreground">generated by AI,</span>
            <br />
            <span className="text-brand">signed by the group.</span>
          </h1>
          <p className="mt-6 max-w-[520px] text-lg leading-relaxed text-muted-foreground">
            Type one sentence. We design the cover, draft the note, and pass it
            around for the whole team to sign — before it lands on the birthday
            desk.
          </p>
          <div className="mt-8 flex flex-wrap gap-3">
            <Link href="/create">
              <Button variant="brand" size="lg">
                Start a card — free
              </Button>
            </Link>
            <Link href="/auth/login">
              <Button variant="outline" size="lg">
                I have an account
              </Button>
            </Link>
          </div>
          <div className="mt-10 flex flex-wrap items-center gap-5 font-mono text-xs tracking-[0.15em] text-muted-foreground/60 uppercase">
            Trusted by teams at
            <div className="flex gap-5 font-sans text-sm font-semibold tracking-tight text-muted-foreground">
              <span>Notion</span>
              <span>Linear</span>
              <span>Vercel</span>
              <span>Ramp</span>
            </div>
          </div>
        </div>

        {/* Demo panel */}
        <div className="hidden overflow-hidden rounded-2xl border border-border bg-card shadow-[0_40px_80px_-40px_rgba(17,17,16,0.14)] lg:block">
          <div className="flex items-center gap-2 border-b border-border px-4 py-3 font-mono text-[11px] tracking-widest text-muted-foreground/60 uppercase">
            <div className="flex gap-1.5">
              <div className="h-2.5 w-2.5 rounded-full bg-border" />
              <div className="h-2.5 w-2.5 rounded-full bg-border" />
              <div className="h-2.5 w-2.5 rounded-full bg-border" />
            </div>
            Live preview
          </div>
          <div className="p-5">
            <div className="rounded-xl bg-background p-3.5 text-sm leading-relaxed text-foreground">
              <span className="text-muted-foreground">Describe the card.</span>
              <br />
              Mira turns 30 on Thursday — she&apos;s on the design team, loves
              botanical illustration and long train rides.
            </div>
            {/* Card preview */}
            <div className="mx-auto mt-6 mb-4 w-[200px]">
              <div
                className="relative w-full overflow-hidden rounded-xl shadow-[0_12px_32px_-8px_rgba(17,17,16,0.22)]"
                style={{ aspectRatio: "3/4" }}
              >
                <div
                  className="absolute inset-0"
                  style={{
                    background:
                      "linear-gradient(135deg, oklch(0.85 0.12 45) 0%, oklch(0.75 0.15 25) 60%, oklch(0.65 0.18 15) 100%)",
                  }}
                />
                <div className="absolute inset-0 flex flex-col justify-end p-4">
                  <div className="text-xs leading-snug font-medium text-white/90">
                    Happy Birthday,
                    <br />
                    <span className="text-base font-semibold">Mira</span>
                  </div>
                </div>
              </div>
            </div>
            <div className="flex flex-wrap gap-2">
              {[
                "Try warmer",
                "Bolder type",
                "More botanical",
                "Regenerate",
              ].map((c) => (
                <div
                  key={c}
                  className="cursor-pointer rounded-full border border-border px-3 py-1.5 text-xs text-muted-foreground transition-colors hover:border-foreground/20 hover:text-foreground"
                >
                  {c}
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Browse by occasion */}
      <section className="border-t border-border">
        <div className="mx-auto max-w-7xl px-6">
          <div className="flex gap-0 overflow-x-auto">
            {OCCASIONS.map((o) => (
              <button
                key={o.id}
                onClick={() => setActiveOccasion(o.id)}
                className={`flex shrink-0 items-center gap-2.5 border-b-2 px-5 py-4 text-sm transition-colors ${
                  activeOccasion === o.id
                    ? "border-foreground text-foreground"
                    : "border-transparent text-muted-foreground hover:text-foreground"
                }`}
              >
                <span
                  className="h-5 w-5 rounded-md"
                  style={{
                    background: `oklch(0.88 0.1 ${o.hue})`,
                  }}
                />
                {o.label}
              </button>
            ))}
          </div>
        </div>
      </section>

      {/* Big statement */}
      <section className="border-t border-border">
        <div className="mx-auto max-w-7xl px-6 py-20">
          <p className="font-mono text-[11px] tracking-[0.15em] text-brand uppercase">
            Built for group cards
          </p>
          <h2 className="mt-4 max-w-3xl text-4xl leading-[1.02] font-semibold tracking-[-0.03em] md:text-5xl lg:text-6xl">
            The card used to take ten Slack messages. Now it takes one link.
          </h2>
          <div className="mt-12 grid grid-cols-1 gap-8 md:grid-cols-3">
            {FEATURES.map((f) => (
              <div key={f.n}>
                <div className="font-mono text-sm text-muted-foreground/60">
                  {f.n}
                </div>
                <h3 className="mt-2 text-lg font-semibold tracking-[-0.015em]">
                  {f.title}
                </h3>
                <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
                  {f.desc}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA section */}
      <section className="border-t border-border bg-secondary/50">
        <div className="mx-auto max-w-4xl px-6 py-24 text-center">
          <h2 className="text-4xl font-semibold tracking-[-0.03em]">
            Ready to create your first card?
          </h2>
          <p className="mx-auto mt-4 max-w-md text-lg leading-relaxed text-muted-foreground">
            Start creating now — no account needed until you&apos;re ready to
            save.
          </p>
          <div className="mt-8 flex flex-wrap justify-center gap-3">
            <Link href="/create">
              <Button variant="brand" size="lg">
                Start a card — free
              </Button>
            </Link>
            <Link href="/auth/sign-up">
              <Button variant="outline" size="lg">
                Create an account
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border py-10">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6">
          <Logo />
          <p className="text-sm text-muted-foreground">
            Create beautiful greeting cards with AI
          </p>
        </div>
      </footer>
    </div>
  )
}
