"use client"

import { createClient } from "@/lib/supabase/client"
import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Logo } from "@/components/logo"

const DEMO_STATES = {
  default: {
    imageUrl: "/demo/card-default.png",
    greeting: "Happy Birthday,",
    name: "Mira",
    message: "Here's to making 30 look completely effortless.",
  },
  Warmer: {
    imageUrl: "/demo/card-warmer.png",
    greeting: "Warmest wishes,",
    name: "Mira",
    message: "May your 30th be as radiant and wonderful as you are.",
  },
  Sassier: {
    imageUrl: "/demo/card-sassier.png",
    greeting: "30 never looked so good -",
    name: "Mira",
    message: "Let's be honest, you've always been the coolest one in the room.",
  },
  Shorter: {
    imageUrl: "/demo/card-shorter.png",
    greeting: "Happy 30th,",
    name: "Mira",
    message: "Make it a good one.",
  },
  Friendlier: {
    imageUrl: "/demo/card-friendlier.png",
    greeting: "Hip hip hooray!",
    name: "Mira",
    message: "So glad you're on our team - today is all yours!",
  },
} as const

const FEATURES = [
  {
    n: "01",
    title: "One link, everyone signs",
    desc: "Each person places their note anywhere on the page. Drag, resize, rotate, add a GIF.",
  },
  {
    n: "02",
    title: "AI drafts first, you edit",
    desc: "Regenerate any line, any cover, any time. The AI has a light touch. Never saccharine.",
  },
  {
    n: "03",
    title: "Private until send",
    desc: "No one sees the card until you decide it's full. Then it arrives, beautifully, in one email.",
  },
]

export default function HomePage() {
  const router = useRouter()
  const supabase = createClient()
  const [loading, setLoading] = useState(true)
  const [demoKey, setDemoKey] = useState<keyof typeof DEMO_STATES>("default")
  const demo = DEMO_STATES[demoKey]

  useEffect(() => {
    const checkUser = async () => {
      const {
        data: { session },
      } = await supabase.auth.getSession()

      if (session) {
        router.replace("/dashboard")
        return
      }

      setLoading(false)
    }

    checkUser()
  }, [router, supabase])

  if (loading) {
    return null
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-50 border-b border-border bg-background/95 backdrop-blur-sm">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-[18px]">
          <div className="flex items-center gap-8">
            <Logo />
            {/* <nav className="hidden items-center gap-6 text-sm text-muted-foreground md:flex"> */}
            {/* <Link
                href="/create"
                className="transition-colors hover:text-foreground"
              >
                Browse
              </Link>
              <span className="cursor-default transition-colors hover:text-foreground">
                How it works
              </span>
              <span className="cursor-default transition-colors hover:text-foreground">
                For teams
              </span>
            </nav> */}
          </div>
          <div className="flex items-center gap-3">
            <Link
              href="/auth/login"
              className="text-sm text-muted-foreground transition-colors hover:text-foreground"
            >
              Sign in
            </Link>
            <Link href="/create">
              <Button variant="brand" size="sm">
                Start a card
              </Button>
            </Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="mx-auto grid max-w-7xl grid-cols-1 items-center gap-12 px-6 py-20 lg:grid-cols-[1.15fr_1fr] lg:gap-16 lg:py-20">
        <div>
          <h1 className="mt-5 text-4xl leading-[0.95] font-semibold tracking-[-0.04em] text-balance md:text-5xl lg:text-[80px] xl:text-[96px]">
            Greeting cards,
            <br />
            <span className="text-muted-foreground">generated by AI, </span>
            <span className="text-brand">signed by the group.</span>
          </h1>
          <p className="mt-6 max-w-[520px] text-lg leading-relaxed text-muted-foreground">
            Type one sentence. We design the cover, draft the note, and pass it
            around for the whole team to sign, before it lands on the birthday
            desk.
          </p>
          <div className="mt-8 flex flex-wrap gap-3">
            <Link href="/create">
              <Button variant="brand" size="lg">
                Start a card
                <span className="rounded-full bg-white/20 px-2 py-0.5 text-xs font-semibold">
                  Free
                </span>
              </Button>
            </Link>
            <Link href="/auth/login">
              <Button variant="outline" size="lg">
                Sign in
              </Button>
            </Link>
          </div>
          {/* <div className="mt-10 flex flex-wrap items-center gap-5 font-mono text-xs tracking-[0.15em] text-muted-foreground/60 uppercase">
            Trusted by teams at
            <div className="flex gap-5 font-sans text-sm font-semibold tracking-tight text-muted-foreground">
              <span>Notion</span>
              <span>Linear</span>
              <span>Vercel</span>
              <span>Ramp</span>
            </div>
          </div> */}
        </div>

        {/* Demo panel */}
        <div className="hidden overflow-hidden rounded-2xl border border-border bg-card shadow-[0_40px_80px_-40px_rgba(17,17,16,0.14)] lg:block">
          <div className="flex items-center gap-2 border-b border-border px-4 py-3 font-mono text-[11px] tracking-widest text-muted-foreground/60 uppercase">
            <div className="flex gap-1.5">
              <div className="h-2.5 w-2.5 rounded-full bg-border" />
              <div className="h-2.5 w-2.5 rounded-full bg-border" />
              <div className="h-2.5 w-2.5 rounded-full bg-border" />
            </div>
            Live preview
          </div>
          <div className="p-5">
            <div className="rounded-xl bg-background p-3.5 text-sm leading-relaxed text-foreground">
              <span className="text-muted-foreground">Describe the card.</span>
              <br />
              Mira turns 30 on Thursday. She&apos;s on the design team, loves
              botanical illustration and long train rides.
            </div>
            {/* Card preview */}
            <div className="mx-auto mt-6 mb-4 w-[200px]">
              <div
                className="relative w-full overflow-hidden rounded-xl shadow-[0_12px_32px_-8px_rgba(17,17,16,0.22)]"
                style={{ aspectRatio: "3/4" }}
              >
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  key={demo.imageUrl}
                  src={demo.imageUrl}
                  alt=""
                  className="absolute inset-0 h-full w-full object-cover"
                />
                <div className="absolute inset-0 bg-linear-to-t from-black/60 via-black/10 to-transparent" />
                <div className="absolute inset-0 flex flex-col justify-end p-4">
                  <p className="text-[10px] leading-snug text-white/80">
                    {demo.greeting}
                  </p>
                  <p className="text-sm font-semibold text-white">
                    {demo.name}
                  </p>
                  <p className="mt-1 text-[9px] leading-relaxed text-white/70">
                    {demo.message}
                  </p>
                </div>
              </div>
            </div>
            <div className="flex flex-wrap gap-2">
              {(["Warmer", "Sassier", "Shorter", "Friendlier"] as const).map(
                (c) => (
                  <button
                    key={c}
                    onClick={() => setDemoKey(c)}
                    className={`cursor-pointer rounded-full border px-3 py-1.5 text-xs transition-colors ${
                      demoKey === c
                        ? "border-foreground/30 bg-foreground/5 text-foreground"
                        : "border-border text-muted-foreground hover:border-foreground/20 hover:text-foreground"
                    }`}
                  >
                    {c}
                  </button>
                ),
              )}
            </div>
          </div>
        </div>
      </section>

      {/* Big statement */}
      <section className="border-t border-border">
        <div className="mx-auto max-w-7xl px-6 py-20">
          <p className="font-mono text-[11px] tracking-[0.15em] text-brand uppercase">
            Built for group cards
          </p>
          <h2 className="mt-4 max-w-3xl text-4xl leading-[1.02] font-semibold tracking-[-0.03em] md:text-5xl lg:text-6xl">
            The card used to take ten follow-ups. Now it takes one link.
          </h2>
          <div className="mt-12 grid grid-cols-1 gap-8 md:grid-cols-3">
            {FEATURES.map((f) => (
              <div key={f.n}>
                <div className="font-mono text-sm text-muted-foreground/60">
                  {f.n}
                </div>
                <h3 className="mt-2 text-lg font-semibold tracking-[-0.015em]">
                  {f.title}
                </h3>
                <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
                  {f.desc}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA section */}
      <section className="border-t border-border bg-secondary/50">
        <div className="mx-auto max-w-4xl px-6 py-24 text-center">
          <h2 className="text-4xl font-semibold tracking-[-0.03em]">
            Start the card. We&apos;ll handle the rest.
          </h2>
          <p className="mx-auto mt-4 max-w-md text-lg leading-relaxed text-muted-foreground">
            No account needed. Just type one sentence and go.
          </p>
          <div className="mt-8 flex flex-wrap justify-center gap-3">
            <Link href="/create">
              <Button variant="brand" size="lg">
                Start a card
                <span className="rounded-full bg-white/20 px-2 py-0.5 text-xs font-semibold">
                  Free
                </span>
              </Button>
            </Link>
            <Link href="/auth/sign-up">
              <Button variant="outline" size="lg">
                Create an account
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border py-10">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6">
          <Logo />
          <p className="text-sm text-muted-foreground">Cards worth signing.</p>
        </div>
      </footer>
    </div>
  )
}
