import Link from "next/link"
import { Logo } from "@/components/logo"
import { getBrowseCategories } from "@/lib/category-pages"
import { COMPARE_CONFIGS } from "@/lib/compare-pages"

type FooterLink = { label: string; href: string }

const OCCASIONS: FooterLink[] = getBrowseCategories().map((cat) => ({
  label: cat.label,
  href: `/browse/${cat.slug}`,
}))

const PRODUCT: FooterLink[] = [
  { label: "Browse", href: "/browse" },
  { label: "Start a card", href: "/create" },
  { label: "For teams", href: "/teams" },
  { label: "Slack app", href: "/slack/install" },
  { label: "Claude connector", href: "/claude" },
  { label: "ChatGPT plugin", href: "/chatgpt" },
  { label: "Support", href: "/support" },
]

const COMPARE: FooterLink[] = Object.values(COMPARE_CONFIGS).map((c) => ({
  label: `vs ${c.competitor}`,
  href: `/compare/${c.slug}`,
}))

const LEGAL: FooterLink[] = [
  { label: "Privacy", href: "/privacy" },
  { label: "Terms", href: "/terms" },
  { label: "Sub-processors", href: "/subprocessors" },
]

function FooterColumn({
  title,
  links,
}: {
  title: string
  links: FooterLink[]
}) {
  return (
    <div>
      <h2 className="text-sm font-semibold tracking-[-0.01em]">{title}</h2>
      <ul className="mt-4 flex flex-col gap-2.5">
        {links.map((link) => (
          <li key={link.href}>
            <Link
              href={link.href}
              className="text-sm text-muted-foreground hover:text-foreground"
            >
              {link.label}
            </Link>
          </li>
        ))}
      </ul>
    </div>
  )
}

export function SiteFooter() {
  return (
    <footer className="border-t border-border">
      <div className="mx-auto max-w-360 px-6 py-12 md:px-15">
        <div className="grid grid-cols-2 gap-10 md:grid-cols-4 lg:grid-cols-[1fr_auto_auto_auto_auto] lg:gap-x-14">
          {/* Brand */}
          <div className="col-span-2 md:col-span-4 lg:col-span-1">
            <Logo className="justify-start" />
            <p className="mt-4 max-w-65 text-sm leading-relaxed text-muted-foreground">
              Group greeting cards, generated by AI and signed by everyone. One
              link, every occasion, kept for good
            </p>
          </div>

          <FooterColumn title="Occasions" links={OCCASIONS} />
          <FooterColumn title="Product" links={PRODUCT} />
          <FooterColumn title="Compare" links={COMPARE} />
          <FooterColumn title="Legal" links={LEGAL} />
        </div>

        <div className="mt-10 border-t border-border pt-8">
          <p className="text-sm text-muted-foreground">Cards worth signing.</p>
        </div>
      </div>
    </footer>
  )
}
