import Link from "next/link"
import { Logo } from "@/components/logo"
import { getBrowseCategories } from "@/lib/category-pages"
import { COMPARE_CONFIGS } from "@/lib/compare-pages"

const OCCASIONS = getBrowseCategories().map((cat) => ({
  label: cat.label,
  href: `/browse/${cat.slug}`,
}))

export function SiteFooter() {
  return (
    <footer className="border-t border-border">
      <div className="mx-auto max-w-[1440px] px-6 py-12 md:px-15">
        <div className="grid grid-cols-1 gap-10 sm:grid-cols-2 lg:grid-cols-[1fr_auto_auto]">
          {/* Brand */}
          <div>
            <Logo className="justify-start" />
            <p className="mt-4 max-w-[260px] text-sm leading-relaxed text-muted-foreground">
              Group greeting cards, generated by AI and signed by everyone. One
              link, every occasion, kept for good
            </p>
          </div>

          {/* Occasions */}
          <div>
            <h4 className="text-sm font-semibold tracking-[-0.01em]">
              Occasions
            </h4>
            <ul className="mt-4 flex flex-col gap-2.5">
              {OCCASIONS.map((o) => (
                <li key={o.href}>
                  <Link
                    href={o.href}
                    className="text-sm text-muted-foreground hover:text-foreground"
                  >
                    {o.label}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          {/* Product / legal */}
          <div>
            <h4 className="text-sm font-semibold tracking-[-0.01em]">
              Product
            </h4>
            <ul className="mt-4 flex flex-col gap-2.5">
              <li>
                <Link
                  href="/browse"
                  className="text-sm text-muted-foreground hover:text-foreground"
                >
                  Browse
                </Link>
              </li>
              <li>
                <Link
                  href="/create"
                  className="text-sm text-muted-foreground hover:text-foreground"
                >
                  Start a card
                </Link>
              </li>
              <li>
                <Link
                  href="/slack/install"
                  className="text-sm text-muted-foreground hover:text-foreground"
                >
                  Slack app
                </Link>
              </li>
              {Object.values(COMPARE_CONFIGS).map((c) => (
                <li key={c.slug}>
                  <Link
                    href={`/compare/${c.slug}`}
                    className="text-sm text-muted-foreground hover:text-foreground"
                  >
                    vs {c.competitor}
                  </Link>
                </li>
              ))}
              <li>
                <Link
                  href="/privacy"
                  className="text-sm text-muted-foreground hover:text-foreground"
                >
                  Privacy
                </Link>
              </li>
              <li>
                <Link
                  href="/terms"
                  className="text-sm text-muted-foreground hover:text-foreground"
                >
                  Terms
                </Link>
              </li>
              <li>
                <Link
                  href="/subprocessors"
                  className="text-sm text-muted-foreground hover:text-foreground"
                >
                  Sub-processors
                </Link>
              </li>
            </ul>
          </div>
        </div>

        <div className="mt-10 border-t border-border pt-8">
          <p className="text-sm text-muted-foreground">Cards worth signing.</p>
        </div>
      </div>
    </footer>
  )
}
