export interface CategoryGalleryItem {
  gradient: string
  pill: string
  forText: string
  sigCount: string
  title: string
  subtitle: string
}

export interface CategoryStep {
  n: string
  title: string
  desc: string
}

export interface CategoryUseCase {
  /** Backdrop hue of the use case's tile (blends 30° on, like the browse tiles). */
  hue: number
  /** Headline on the tile's mockup card. */
  headline: string
  /** Null until art is generated; the tile shows a plain cover in its hue meanwhile. */
  coverImage: string | null
  title: string
  desc: string
}

export interface CategoryFAQ {
  q: string
  a: string
}

export interface CategoryConfig {
  slug: string
  /** ISO date for the sitemap; bump when the page's content changes meaningfully. */
  lastModified: string
  label: string
  shortDesc: string

  // Meta
  metaTitle: string
  metaDescription: string

  // Hero
  badge: string
  h1Line1: string
  h1Muted: string
  h1Pop: string
  lede: string
  ctaText: string

  // Card visual
  frontGradient: string
  cardTitle: string
  /** Cover art for the mockup card on the browse tile (generated by the app's own image
   * model), and the hue of its plain fallback cover, well apart from `frontGradient`.
   * Null until art is generated for the occasion. */
  coverImage: string | null
  coverHue: number
  /** Inside the hero's interactive card: who it's for, the opening note and a few
   * signatures. */
  sampleRecipient: string
  sampleMessage: string
  sampleNotes: { message: string; font: string; color: string }[]

  // Gallery (not shown yet; see the gallery TODO in `category-landing-page.tsx`)
  galleryEyebrow?: string
  galleryTitle?: string
  gallerySub?: string
  gallery?: CategoryGalleryItem[]

  // How it works
  howTitle: string
  howSub: string
  steps: CategoryStep[]

  // Use cases
  usesEyebrow: string
  usesTitle: string
  uses: CategoryUseCase[]

  // FAQ
  faqEyebrow: string
  faqTitle: string
  faqs: CategoryFAQ[]

  // CTA band
  ctaBandTitle: string
  ctaBandSub: string
}

export const CATEGORY_CONFIGS: Record<string, CategoryConfig> = {
  birthday: {
    slug: "birthday",
    lastModified: "2026-09-29",
    label: "Birthday cards",
    shortDesc:
      "For the team, the family group chat, and the one they won't forget",

    metaTitle: "Group Birthday Cards for Coworkers",
    metaDescription:
      "Create a group birthday card online in seconds. Everyone signs from one link, AI drafts the cover and note, and it arrives as one beautiful card, by email or text. Free to start.",

    badge: "The group birthday card, minus the reply-all",
    h1Line1: "Group birthday cards,",
    h1Muted: "signed by everyone,",
    h1Pop: "sent as one",
    lede: "Start an online birthday card, share one link, and the whole team signs from their own phone. The AI drafts the cover and the opening note. You just pick who it's for",
    ctaText: "Start a birthday card",

    frontGradient:
      "linear-gradient(135deg, oklch(0.88 0.08 18), oklch(0.82 0.09 48))",
    cardTitle: "Happy Birthday, Mira",
    coverImage: "/occasions/birthday.webp",
    coverHue: 280,
    sampleRecipient: "Mira",
    sampleMessage:
      "Mira, happy 30th! Here's to botanical sketches, long lunches and the best year yet. Love, the whole team",
    sampleNotes: [
      {
        message: "Happy birthday! Cake is on me this time",
        font: "caveat",
        color: "#b4452f",
      },
      {
        message: "30 looks great on you, Mira",
        font: "dancing-script",
        color: "#3f5aa8",
      },
      {
        message: "Have the best day! Sam x",
        font: "pacifico",
        color: "#2f7d5b",
      },
    ],

    galleryEyebrow: "Birthday card examples",
    galleryTitle: "Birthday cards people actually kept",
    gallerySub:
      "Every cover is generated from a single sentence, then edited until it's right. Here are real birthday cards sent through CardShare.ai for coworkers, parents, best friends, and the group chat",
    gallery: [
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.08 18), oklch(0.82 0.09 48))",
        pill: "Coworker",
        forText: "For Mira",
        sigCount: "14 signatures",
        title: "Happy Birthday, Mira",
        subtitle: "Botanical · warm · the design team",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.08 330), oklch(0.82 0.09 360))",
        pill: "For Mom",
        forText: "For Mom",
        sigCount: "6 signatures",
        title: "Happy Birthday, Mom",
        subtitle: "Soft · heartfelt · us kids",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.08 70), oklch(0.82 0.09 110))",
        pill: "Milestone · 30th",
        forText: "For Jonas",
        sigCount: "22 signatures",
        title: "Thirty looks good on you",
        subtitle: "Bold · celebratory · the whole floor",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.07 250), oklch(0.82 0.08 280))",
        pill: "Best friend",
        forText: "For Elise",
        sigCount: "11 signatures",
        title: "Another trip around the sun",
        subtitle: "Playful · inside-jokes · the brunch club",
      },
    ],

    howTitle: "From one sentence to a signed card in minutes",
    howSub:
      "The birthday card used to take ten Slack messages and a folded piece of paper passed around the office. Now it takes one link",
    steps: [
      {
        n: "01",
        title: "Describe the birthday",
        desc: 'Tell us who it\'s for in a sentence e.g. "Mira turns 30 Thursday, loves botanical illustration." The AI drafts a cover and an opening note you can regenerate any time',
      },
      {
        n: "02",
        title: "Share one link, everyone signs",
        desc: "Drop the link in your group chat. Each person adds their note from their own phone, picks an ink color, and can add a GIF. It stays private until you send",
      },
      {
        n: "03",
        title: "Send it on the big day",
        desc: "When the card is full, send it on the morning of the birthday by email or a shareable link. It opens beautifully in the browser with every signature",
      },
    ],

    usesEyebrow: "Birthday cards for every kind of person",
    usesTitle: "Pick the one you need",
    uses: [
      {
        hue: 18,
        headline: "Happy Birthday, Priya",
        coverImage: "/occasions/uses/birthday-1.webp",
        title: "Birthday cards for coworkers",
        desc: "The office classic. One link the whole team signs without anyone leaving their desk",
      },
      {
        hue: 70,
        headline: "Happy Birthday, Mark",
        coverImage: "/occasions/uses/birthday-2.webp",
        title: "Birthday cards for your boss",
        desc: "Sincere, considered, never sycophantic. The AI keeps the tone exactly right",
      },
      {
        hue: 130,
        headline: "Happy 40th, Leo",
        coverImage: "/occasions/uses/birthday-3.webp",
        title: "Milestone birthday cards",
        desc: "30th, 40th, 50th, 60th. Big-deal covers and copy that marks the moment",
      },
      {
        hue: 190,
        headline: "Happy Birthday, Zoe",
        coverImage: "/occasions/uses/birthday-4.webp",
        title: "Birthday cards for friends",
        desc: "Inside jokes, GIFs, the works. Made for the whole group chat to pile on",
      },
      {
        hue: 250,
        headline: "Happy Birthday, Mom",
        coverImage: "/occasions/uses/birthday-5.webp",
        title: "Birthday cards for family",
        desc: "For Mom, Dad, a sibling, or the group of cousins. Warm, personal, kept for years",
      },
      {
        hue: 330,
        headline: "Belated wishes, Sam",
        coverImage: "/occasions/uses/birthday-6.webp",
        title: "Belated birthday cards",
        desc: "Missed it by a day or a week? Owning it warmly beats pretending you didn't",
      },
    ],

    faqEyebrow: "Birthday card FAQs",
    faqTitle: "Everything about sending one",
    faqs: [
      {
        q: "How do group birthday cards work?",
        a: "Start a card, share one link, and everyone adds their note from their own phone or laptop. No one sees the card until you decide it's full and send it. It arrives as a single, beautifully laid-out card when you send it.",
      },
      {
        q: "Can everyone sign the same birthday card online?",
        a: "Yes. There's no limit on signers. Each person places their message anywhere on the page, picks an ink color, and can add a GIF. The card stays completely private until you send it.",
      },
      {
        q: "Is CardShare.ai free?",
        a: "Yes. You can design a card, collect signatures, and send it for free, and nobody who signs needs an account.",
      },
      {
        q: "How do I send a birthday card by email or text?",
        a: "When the card's ready, enter the recipient's email address or copy a shareable link to drop into a text. They open it right in the browser. Nothing to download or install.",
      },
      {
        q: "Can I set the card up before their birthday?",
        a: "Yes. Start it weeks ahead and leave the link open while people sign. Nothing is sent until you decide it's ready, so you can send it on the morning of the birthday.",
      },
      {
        q: "Can I add GIFs or a group message?",
        a: "Every signer can add a GIF alongside their note, and the AI can draft a shared opening message that sets the tone for the whole card.",
      },
    ],

    ctaBandTitle: "Whose birthday is coming up?",
    ctaBandSub:
      "Set up the card in two minutes, share the link, and let everyone sign. We'll handle the cover and the layout",
  },

  "thank-you": {
    slug: "thank-you",
    lastModified: "2026-09-29",
    label: "Thank you cards",
    shortDesc: "For the team, the mentor, the neighbor who watched the dog",

    metaTitle: "Group Thank You Cards for Coworkers",
    metaDescription:
      "Create a group thank you card online in seconds. Share one link so the whole team signs, AI drafts the cover and opening note. Delivered beautifully by email or text. Free to start.",

    badge: "Thank you cards that actually land",
    h1Line1: "Group thank you cards,",
    h1Muted: "from the whole team,",
    h1Pop: "genuinely felt",
    lede: "Start a thank you card, share one link, and watch the whole team pile on with heartfelt notes. The AI drafts the cover and sets the tone. You just name who deserves it",
    ctaText: "Start a thank you card",

    frontGradient:
      "linear-gradient(135deg, oklch(0.88 0.07 170), oklch(0.82 0.08 200))",
    cardTitle: "Thank you, Alex",
    coverImage: "/occasions/thank-you.webp",
    coverHue: 18,
    sampleRecipient: "Alex",
    sampleMessage:
      "Alex, thank you for a year of patient answers, calm Fridays and endless tea. We couldn't have done it without you",
    sampleNotes: [
      {
        message: "You made every launch feel easy",
        font: "caveat",
        color: "#3f5aa8",
      },
      {
        message: "Thank you for always making time",
        font: "dancing-script",
        color: "#b4452f",
      },
      {
        message: "The best mentor, full stop. Jo",
        font: "pacifico",
        color: "#2f7d5b",
      },
    ],

    galleryEyebrow: "Thank you card examples",
    galleryTitle: "Thank you cards worth reading twice",
    gallerySub:
      "From mentor appreciation to team shout-outs, these are real thank you cards sent through CardShare.ai. Every cover generated from one sentence, every note from the heart",
    gallery: [
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.07 170), oklch(0.82 0.08 200))",
        pill: "For mentor",
        forText: "For Alex",
        sigCount: "8 signatures",
        title: "Thank you, Alex",
        subtitle: "Warm · genuine · the whole cohort",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.07 140), oklch(0.82 0.08 170))",
        pill: "For the team",
        forText: "For the team",
        sigCount: "16 signatures",
        title: "You all made it happen",
        subtitle: "Celebratory · heartfelt · from leadership",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.06 200), oklch(0.82 0.07 230))",
        pill: "Volunteer",
        forText: "For Sophie",
        sigCount: "12 signatures",
        title: "Thank you for everything",
        subtitle: "Sincere · personal · the whole org",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.07 110), oklch(0.82 0.08 140))",
        pill: "Personal",
        forText: "For Raj",
        sigCount: "4 signatures",
        title: "We couldn't have done it",
        subtitle: "Intimate · specific · a close team",
      },
    ],

    howTitle: "From one sentence to a heartfelt group card",
    howSub:
      "Getting a whole team to say thank you used to mean chasing people for signatures. Now it takes one link and five minutes",
    steps: [
      {
        n: "01",
        title: "Name who you're thanking",
        desc: "Tell us who it's for and why. One sentence is enough. The AI writes a cover and an opening note that captures the moment without being over the top",
      },
      {
        n: "02",
        title: "Share one link, everyone adds their note",
        desc: "Send the link to your team, the group chat, or the whole org. Each person signs from their own device, adds their message, and can include a GIF",
      },
      {
        n: "03",
        title: "Send it when you're ready",
        desc: "When everyone's signed, deliver it by email or shareable link. It arrives as one beautiful card, with every note and signature laid out perfectly",
      },
    ],

    usesEyebrow: "Thank you cards for every kind of person",
    usesTitle: "Who are you thanking?",
    uses: [
      {
        hue: 70,
        headline: "Thank you, Nina",
        coverImage: "/occasions/uses/thank-you-1.webp",
        title: "Thank you cards for coworkers",
        desc: "For the colleague who covered for you, saved the launch, or just always shows up",
      },
      {
        hue: 130,
        headline: "Thank you, Omar",
        coverImage: "/occasions/uses/thank-you-2.webp",
        title: "Thank you cards for managers",
        desc: "A group card from the whole team tells them more than a one-liner in Slack ever could",
      },
      {
        hue: 190,
        headline: "Thank you, Ruth",
        coverImage: "/occasions/uses/thank-you-3.webp",
        title: "Thank you cards for retiring colleagues",
        desc: "Send them off with a card full of notes from everyone they worked with over the years",
      },
      {
        hue: 250,
        headline: "Thank you, Ms. Lee",
        coverImage: "/occasions/uses/thank-you-4.webp",
        title: "Thank you cards for teachers",
        desc: "From the whole class, the whole parent group, or just the students who meant it most",
      },
      {
        hue: 330,
        headline: "Thank you, Jo",
        coverImage: "/occasions/uses/thank-you-5.webp",
        title: "Thank you cards for volunteers",
        desc: "Recognize the people who gave their time with something more than a quick mention",
      },
      {
        hue: 18,
        headline: "Thank you, Acme team",
        coverImage: "/occasions/uses/thank-you-6.webp",
        title: "Thank you cards for clients",
        desc: "Professional, warm, and personal. A signed card from the whole account team stands out",
      },
    ],

    faqEyebrow: "Thank you card FAQs",
    faqTitle: "Everything about sending one",
    faqs: [
      {
        q: "How do group thank you cards work?",
        a: "Start a card, share one link with your team or group, and everyone adds their own note from their own device. The card stays private until you send it. It arrives as one complete, laid-out card.",
      },
      {
        q: "Can the whole team sign the same thank you card?",
        a: "Yes, there's no limit on signers. Each person adds their note, picks their ink color, and can attach a GIF. It all comes together in one card.",
      },
      {
        q: "What's the right tone for a professional thank you card?",
        a: "The AI defaults to warm and sincere without being over the top. You can regenerate the cover message any time, or edit it word by word to get the tone exactly right for the person.",
      },
      {
        q: "Can I send a thank you card to someone outside the company?",
        a: "Yes. The recipient gets a link they open in the browser. No account needed. You can send it by email or share a link via any channel.",
      },
      {
        q: "How quickly can I set one up?",
        a: "The whole thing (card, cover, opening message, signature link) takes about two minutes to create. Collecting signatures is up to you, but people usually sign within the hour.",
      },
      {
        q: "Is it free to send a group thank you card?",
        a: "Yes. You can design a card, collect signatures, and send it for free, and nobody who signs needs an account.",
      },
    ],

    ctaBandTitle: "Who deserves a thank you today?",
    ctaBandSub:
      "Set up the card in two minutes, share the link, and let everyone pile on. We'll handle the cover, the layout, and the delivery",
  },

  "work-anniversary": {
    slug: "work-anniversary",
    lastModified: "2026-09-29",
    label: "Work anniversary cards",
    shortDesc: "One year or ten, mark the milestone with the whole team",

    metaTitle: "Group Work Anniversary Cards for Coworkers",
    metaDescription:
      "Create a group work anniversary card online. Share one link so the whole team signs, AI crafts the cover and note for 1, 5, or 10+ year milestones. Free to start.",

    badge: "Make the milestone mean something",
    h1Line1: "Work anniversary cards,",
    h1Muted: "from the whole team,",
    h1Pop: "worth keeping",
    lede: "Start a work anniversary card, share one link, and let everyone add a note, from the newest hire to the CEO. The AI marks the milestone with the weight it deserves",
    ctaText: "Start an anniversary card",

    frontGradient:
      "linear-gradient(135deg, oklch(0.88 0.08 70), oklch(0.82 0.09 110))",
    cardTitle: "Five years, James",
    coverImage: "/occasions/work-anniversary.webp",
    coverHue: 250,
    sampleRecipient: "James",
    sampleMessage:
      "Five years, James! Thank you for every trail you've blazed and every coffee you've made for the team",
    sampleNotes: [
      { message: "Here's to five more!", font: "pacifico", color: "#b4452f" },
      {
        message: "Couldn't imagine the team without you",
        font: "caveat",
        color: "#3f5aa8",
      },
      {
        message: "Congrats on the milestone. Priya",
        font: "dancing-script",
        color: "#2f7d5b",
      },
    ],

    galleryEyebrow: "Work anniversary card examples",
    galleryTitle: "Anniversary cards that mark the moment properly",
    gallerySub:
      "From one-year welcomes to decade-long tributes, these are work anniversary cards sent through CardShare.ai: milestone-worthy covers, notes from the whole team",
    gallery: [
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.08 70), oklch(0.82 0.09 110))",
        pill: "5 years",
        forText: "For James",
        sigCount: "18 signatures",
        title: "Five years of showing up",
        subtitle: "Sincere · milestone · the whole department",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.07 50), oklch(0.82 0.08 80))",
        pill: "10 years",
        forText: "For Sarah",
        sigCount: "26 signatures",
        title: "A decade of making us better",
        subtitle: "Warm · tribute · the whole company",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.07 100), oklch(0.82 0.08 130))",
        pill: "1 year",
        forText: "For Marcus",
        sigCount: "9 signatures",
        title: "One year down, many more to come",
        subtitle: "Welcoming · warm · the team",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.07 40), oklch(0.82 0.08 70))",
        pill: "Remote team",
        forText: "For Priya",
        sigCount: "14 signatures",
        title: "Three years, three time zones",
        subtitle: "Playful · global · distributed team",
      },
    ],

    howTitle: "From one sentence to a milestone card",
    howSub:
      "Work anniversaries used to get a generic auto-email. Now the whole team can sign something that actually means something",
    steps: [
      {
        n: "01",
        title: "Note the anniversary",
        desc: "Tell us who it's for and how long they've been around. \"Sarah hits ten years this Thursday, she built the whole CS team.\" The AI drafts a cover and note that honors the milestone",
      },
      {
        n: "02",
        title: "The whole team signs",
        desc: "Share one link with everyone: remote, in-office, across time zones. Each person adds their message, picks an ink color, and can add a GIF",
      },
      {
        n: "03",
        title: "Deliver it on the day",
        desc: "Send it on the anniversary date by email or shareable link. It arrives as one beautifully composed card, every note included",
      },
    ],

    usesEyebrow: "Anniversary cards for every milestone",
    usesTitle: "How long have they been with you?",
    uses: [
      {
        hue: 130,
        headline: "One year, Ben",
        coverImage: "/occasions/uses/work-anniversary-1.webp",
        title: "One-year anniversary cards",
        desc: "A warm welcome into the fold. Mark the first year with something more than a calendar reminder",
      },
      {
        hue: 190,
        headline: "Five years, Sarah",
        coverImage: "/occasions/uses/work-anniversary-2.webp",
        title: "Five-year milestone cards",
        desc: "Half a decade is a big deal. Give it the weight it deserves with notes from the whole team",
      },
      {
        hue: 250,
        headline: "Ten years, Raj",
        coverImage: "/occasions/uses/work-anniversary-3.webp",
        title: "Ten-year (and beyond) cards",
        desc: "A decade of showing up. The whole company signs, and the AI helps every note say something real",
      },
      {
        hue: 330,
        headline: "Happy anniversary, Kim",
        coverImage: "/occasions/uses/work-anniversary-4.webp",
        title: "Remote team anniversary cards",
        desc: "Distance doesn't matter. One link, everyone signs from wherever they are",
      },
      {
        hue: 18,
        headline: "Three years, Elena",
        coverImage: "/occasions/uses/work-anniversary-5.webp",
        title: "Manager anniversary cards",
        desc: "From the whole team they've built. A card full of notes is the best kind of leadership feedback",
      },
      {
        hue: 70,
        headline: "Twenty years, Frank",
        coverImage: "/occasions/uses/work-anniversary-6.webp",
        title: "Long-service recognition cards",
        desc: "For the people who have been around the longest, and made the culture what it is",
      },
    ],

    faqEyebrow: "Work anniversary card FAQs",
    faqTitle: "Everything about marking the milestone",
    faqs: [
      {
        q: "How do group work anniversary cards work?",
        a: "Start a card, share one link with the team, and everyone adds their note from their own device. The card stays private until you send it. It arrives as one beautifully composed card when you send it.",
      },
      {
        q: "Can I set it up in advance?",
        a: "Yes. Create the card and collect signatures at your own pace. Nothing is sent until you decide it's ready, so you can send it on the exact anniversary date.",
      },
      {
        q: "What should I write in a work anniversary card?",
        a: "The AI drafts the opening message for you: warm, specific, and milestone-appropriate. You can regenerate it until it sounds right, or edit it word by word.",
      },
      {
        q: "Can remote team members sign from different time zones?",
        a: "Yes. Each person signs from their own device at their own time. No one needs an account. Just the link.",
      },
      {
        q: "How many people can sign?",
        a: "There's no limit. Whether it's a team of five or a company of five hundred, everyone gets the same link and adds their note.",
      },
      {
        q: "Is it free to send a group work anniversary card?",
        a: "Yes. You can design a card, collect signatures, and send it for free, and nobody who signs needs an account.",
      },
    ],

    ctaBandTitle: "Whose work anniversary is coming up?",
    ctaBandSub:
      "Set up the card in two minutes, share the link, and let the whole team sign. We'll handle the cover, the milestone copy, and the delivery",
  },

  farewell: {
    slug: "farewell",
    lastModified: "2026-09-29",
    label: "Farewell cards",
    shortDesc: "Send someone off with notes from everyone they worked with",

    metaTitle: "Group Farewell & Goodbye Cards for Coworkers",
    metaDescription:
      "Create a group farewell card online. Share one link so the whole team signs a leaving card or goodbye card for a coworker moving on. AI crafts the cover. Free to start.",

    badge: "Send them off the right way",
    h1Line1: "Farewell cards",
    h1Muted: "everyone signs,",
    h1Pop: "they'll always keep",
    lede: "Start a farewell card, share one link, and let everyone add a note, from their first week to their last day. The AI captures the tone of the moment so you don't have to",
    ctaText: "Start a farewell card",

    frontGradient:
      "linear-gradient(135deg, oklch(0.88 0.07 250), oklch(0.82 0.08 285))",
    cardTitle: "Good luck, Dan",
    coverImage: "/occasions/farewell.webp",
    coverHue: 70,
    sampleRecipient: "Dan",
    sampleMessage:
      "Dan, it won't be the same without you. Good luck with the startup and fair winds on the next adventure",
    sampleNotes: [
      { message: "Keep in touch, sailor!", font: "pacifico", color: "#3f5aa8" },
      {
        message: "We'll miss your terrible puns",
        font: "caveat",
        color: "#b4452f",
      },
      {
        message: "Go get 'em, Dan. Nina",
        font: "dancing-script",
        color: "#2f7d5b",
      },
    ],

    galleryEyebrow: "Farewell card examples",
    galleryTitle: "Goodbye cards people actually treasure",
    gallerySub:
      "From leaving the company to heading into retirement, these are farewell cards sent through CardShare.ai: covers that mark the moment, notes from everyone who'll miss them",
    gallery: [
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.07 250), oklch(0.82 0.08 285))",
        pill: "New adventure",
        forText: "For Dan",
        sigCount: "19 signatures",
        title: "Good luck, Dan",
        subtitle: "Warm · bittersweet · the whole team",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.06 230), oklch(0.82 0.07 260))",
        pill: "Retirement",
        forText: "For Margaret",
        sigCount: "24 signatures",
        title: "Here's to what comes next",
        subtitle: "Celebratory · heartfelt · the whole company",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.06 270), oklch(0.82 0.07 300))",
        pill: "Moving cities",
        forText: "For Kai",
        sigCount: "11 signatures",
        title: "The city's loss, their gain",
        subtitle: "Playful · affectionate · close team",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.06 200), oklch(0.82 0.07 230))",
        pill: "Parental leave",
        forText: "For Chloe",
        sigCount: "8 signatures",
        title: "See you on the other side",
        subtitle: "Warm · excited · the department",
      },
    ],

    howTitle: "From one sentence to a proper send-off",
    howSub:
      "The leaving card used to be a slightly damp piece of paper that made the rounds two hours before someone left. This is the version they'll actually keep",
    steps: [
      {
        n: "01",
        title: "Tell us who's leaving",
        desc: "One sentence is enough. \"Dan's leaving Friday after three years, he's joining a startup.\" The AI drafts a cover and an opening note that captures the moment",
      },
      {
        n: "02",
        title: "Drop the link in the group chat",
        desc: "Everyone signs from their own phone or laptop. No chasing, no circulating paper. Each person adds their note, picks an ink color, and can add a GIF",
      },
      {
        n: "03",
        title: "Send it on their last day",
        desc: "Deliver by email or shareable link whenever the time is right. It opens beautifully in the browser, with every note and signature as one card",
      },
    ],

    usesEyebrow: "Farewell cards for every kind of goodbye",
    usesTitle: "What kind of goodbye is this?",
    uses: [
      {
        hue: 190,
        headline: "Good luck, Dan",
        coverImage: "/occasions/uses/farewell-1.webp",
        title: "Leaving the company cards",
        desc: "For the colleague heading somewhere new. One card from everyone they worked with",
      },
      {
        hue: 250,
        headline: "Happy retirement, Pat",
        coverImage: "/occasions/uses/farewell-2.webp",
        title: "Retirement cards",
        desc: "Decades of showing up deserve more than a standard send-off. A card full of notes from the whole company",
      },
      {
        hue: 330,
        headline: "Bon voyage, Lucy",
        coverImage: "/occasions/uses/farewell-3.webp",
        title: "Moving cities cards",
        desc: "A group card from everyone in the office, for the person who's heading somewhere new",
      },
      {
        hue: 18,
        headline: "See you soon, Aisha",
        coverImage: "/occasions/uses/farewell-4.webp",
        title: "Parental leave cards",
        desc: "A warm send-off before their biggest adventure yet. Everyone signs before they head out",
      },
      {
        hue: 70,
        headline: "New chapter, Tom",
        coverImage: "/occasions/uses/farewell-5.webp",
        title: "Career change cards",
        desc: "For the leap into something completely different. The team signs, the AI captures the excitement",
      },
      {
        hue: 130,
        headline: "Thanks for everything",
        coverImage: "/occasions/uses/farewell-6.webp",
        title: "Team restructure cards",
        desc: "When a team disbands or reorganises, give everyone a chance to say something real",
      },
    ],

    faqEyebrow: "Farewell card FAQs",
    faqTitle: "Everything about the goodbye card",
    faqs: [
      {
        q: "How do group farewell cards work?",
        a: "Start a card, share one link, and everyone adds their note from their own device. No one sees it until you decide it's ready to send. It arrives as one card when you send it.",
      },
      {
        q: "Can I keep the card a surprise?",
        a: "Yes. The card is completely private until you choose to send it. Share the signing link with everyone except the person it's for.",
      },
      {
        q: "What should I write in a farewell card?",
        a: "The AI drafts the opening message: warm, specific, appropriate to the situation. You can regenerate it or edit it until it sounds right for the person and the moment.",
      },
      {
        q: "Can I use a photo for the farewell card?",
        a: "Yes. Upload a photo when you create the card and the AI designs the cover from it. Each signer can also add a GIF alongside their note.",
      },
      {
        q: "How many people can sign a leaving card?",
        a: "No limit. Whether it's a team of five or a whole building, everyone gets the same link and adds their own note.",
      },
      {
        q: "Can I choose when it's sent?",
        a: "Yes. Nothing is sent until you decide it's ready, so you can send it on their last day, at their send-off party, or whenever feels right.",
      },
    ],

    ctaBandTitle: "Who's leaving soon?",
    ctaBandSub:
      "Set up the card in two minutes, share the link, and let the team say what they actually feel. We'll handle the cover, the layout, and the delivery",
  },

  wedding: {
    slug: "wedding",
    lastModified: "2026-09-29",
    label: "Wedding cards",
    shortDesc: "Collect warm words from the whole guest list in one keepsake",

    metaTitle: "Group Wedding Cards for Guests",
    metaDescription:
      "Create a group wedding card online. Share one link so every guest signs. AI designs the cover and sets the tone. Delivered beautifully before the big day. Free to start.",

    badge: "One keepsake from everyone who loves them",
    h1Line1: "Wedding cards,",
    h1Muted: "from everyone",
    h1Pop: "who loves them",
    lede: "Start a wedding card, share one link with the whole guest list, and collect heartfelt notes from everyone, wherever they are. The AI designs the cover and sets the tone",
    ctaText: "Start a wedding card",

    frontGradient:
      "linear-gradient(135deg, oklch(0.89 0.05 330), oklch(0.84 0.06 360))",
    cardTitle: "James & Emma",
    coverImage: "/occasions/wedding.webp",
    coverHue: 250,
    sampleRecipient: "James & Emma",
    sampleMessage:
      "James & Emma, wishing you a lifetime of seaside walks, garden dinners and laughter. Congratulations!",
    sampleNotes: [
      {
        message: "So happy for you both!",
        font: "dancing-script",
        color: "#b4452f",
      },
      { message: "Save us a dance", font: "pacifico", color: "#3f5aa8" },
      {
        message: "Cheers to the happy couple. Kim",
        font: "caveat",
        color: "#2f7d5b",
      },
    ],

    galleryEyebrow: "Wedding card examples",
    galleryTitle: "Wedding cards they'll keep forever",
    gallerySub:
      "From intimate weddings to guest lists of hundreds, these are wedding cards created with CardShare.ai: beautiful covers, every guest's note in one keepsake",
    gallery: [
      {
        gradient:
          "linear-gradient(135deg, oklch(0.89 0.05 330), oklch(0.84 0.06 360))",
        pill: "Wedding day",
        forText: "James & Emma",
        sigCount: "42 signatures",
        title: "James & Emma",
        subtitle: "Romantic · elegant · all their guests",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.89 0.05 310), oklch(0.84 0.05 340))",
        pill: "Engagement",
        forText: "Leo & Noor",
        sigCount: "18 signatures",
        title: "You said yes!",
        subtitle: "Joyful · celebratory · friends & family",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.06 20), oklch(0.82 0.07 50))",
        pill: "Destination",
        forText: "Marta & Yusuf",
        sigCount: "28 signatures",
        title: "Love at every latitude",
        subtitle: "Adventurous · warm · the guest list",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.05 350), oklch(0.83 0.06 20))",
        pill: "Small wedding",
        forText: "Phil & Jo",
        sigCount: "9 signatures",
        title: "The most perfect day",
        subtitle: "Intimate · heartfelt · close family",
      },
    ],

    howTitle: "From one sentence to a keepsake card",
    howSub:
      "A card the couple will keep for years. One link, the whole guest list, collected in one beautiful place",
    steps: [
      {
        n: "01",
        title: "Describe the couple",
        desc: "Tell us their names and something about them, and the AI designs a cover and opening note that fits. You can regenerate it as many times as you like",
      },
      {
        n: "02",
        title: "Share the signing link",
        desc: "Share it in the group chat, the wedding WhatsApp, or email it directly. Every guest signs from their own device. No app needed",
      },
      {
        n: "03",
        title: "Deliver before the big day",
        desc: "Send it before the ceremony, on the day itself, or after. It arrives as one complete card, with every note and warm wish beautifully laid out",
      },
    ],

    usesEyebrow: "Wedding cards for every occasion",
    usesTitle: "What are you celebrating?",
    uses: [
      {
        hue: 250,
        headline: "James & Emma",
        coverImage: "/occasions/uses/wedding-1.webp",
        title: "Wedding day cards",
        desc: "The whole guest list in one card. Share a link, everyone signs, the couple keeps it forever",
      },
      {
        hue: 330,
        headline: "Congrats, Mia & Noah",
        coverImage: "/occasions/uses/wedding-2.webp",
        title: "Engagement cards",
        desc: "For the moment they said yes. A card from everyone who wants to celebrate them",
      },
      {
        hue: 18,
        headline: "Cheers, Hannah",
        coverImage: "/occasions/uses/wedding-3.webp",
        title: "Bridal shower cards",
        desc: "The whole party signs before the big day, a warm-up act for the main event",
      },
      {
        hue: 70,
        headline: "Love from afar",
        coverImage: "/occasions/uses/wedding-4.webp",
        title: "Cards from destination guests",
        desc: "For the guests who couldn't make it. A signed card shows they were there in spirit",
      },
      {
        hue: 130,
        headline: "To the wedding party",
        coverImage: "/occasions/uses/wedding-5.webp",
        title: "Wedding party cards",
        desc: "From the bridesmaids, the best men, or both. Something personal before the ceremony",
      },
      {
        hue: 190,
        headline: "Happy anniversary",
        coverImage: "/occasions/uses/wedding-6.webp",
        title: "Anniversary cards",
        desc: "First, fifth, tenth. Collect notes from everyone who's watched them grow together",
      },
    ],

    faqEyebrow: "Wedding card FAQs",
    faqTitle: "Everything about the keepsake card",
    faqs: [
      {
        q: "How do group wedding cards work?",
        a: "Start a card, share one link with the guest list, and everyone adds their note from their own device. You control when the card is sent. It arrives as one beautifully composed keepsake.",
      },
      {
        q: "How many guests can sign?",
        a: "There's no limit. Whether your guest list is ten people or two hundred, everyone gets the same link and adds their own personal note.",
      },
      {
        q: "Can guests add GIFs or personal messages?",
        a: "Yes. Every signer writes their own message and can add a GIF alongside it. The AI can also draft a shared opening note that sets the tone for the whole card.",
      },
      {
        q: "Can I keep it a surprise?",
        a: "Yes. The card stays completely private until you choose to send it, even if dozens of people have already signed.",
      },
      {
        q: "What format does the couple receive it in?",
        a: "They get a link they open in the browser. No app needed. It displays beautifully on any device, with every note laid out as one card.",
      },
      {
        q: "Can I send a wedding card by email?",
        a: "Yes. Enter the recipient's email address and CardShare.ai delivers it directly. Or copy a shareable link to send via text or any other channel.",
      },
    ],

    ctaBandTitle: "Who's getting married?",
    ctaBandSub:
      "Set up the card in two minutes, share the link with the guest list, and collect every warm wish in one place. We'll handle the cover, the layout, and the delivery",
  },

  promotion: {
    slug: "promotion",
    lastModified: "2026-09-29",
    label: "Promotion cards",
    shortDesc: "New title, new chapter. Celebrate it as a group",

    metaTitle: "Group Promotion Cards for Coworkers",
    metaDescription:
      "Create a group promotion or congratulations card online. Share one link so the whole team signs, AI drafts the cover and note. Free to start.",

    badge: "Because a group emoji doesn't do it justice",
    h1Line1: "Congrats cards",
    h1Muted: "for the big moment,",
    h1Pop: "from everyone",
    lede: "Start a congratulations card, share one link, and let the whole team pile on. The AI drafts a cover that marks the occasion. You just describe what they achieved",
    ctaText: "Start a congrats card",

    frontGradient:
      "linear-gradient(135deg, oklch(0.88 0.08 130), oklch(0.82 0.09 160))",
    cardTitle: "Congrats, Aria!",
    coverImage: "/occasions/promotion.webp",
    coverHue: 330,
    sampleRecipient: "Aria",
    sampleMessage:
      "Congrats, Aria! Head of design suits you. Here's to the next summit",
    sampleNotes: [
      { message: "So well deserved!", font: "pacifico", color: "#b4452f" },
      {
        message: "Can't wait to see what you build",
        font: "caveat",
        color: "#3f5aa8",
      },
      {
        message: "Proud of you, boss. Ben",
        font: "dancing-script",
        color: "#2f7d5b",
      },
    ],

    galleryEyebrow: "Congratulations card examples",
    galleryTitle: "Cards for the moments worth celebrating",
    gallerySub:
      "Promotions, new jobs, graduations, new homes: these are congratulations cards sent through CardShare.ai. Every cover designed to mark the moment, every note from the people who mean it",
    gallery: [
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.08 130), oklch(0.82 0.09 160))",
        pill: "Promotion",
        forText: "For Aria",
        sigCount: "14 signatures",
        title: "Congrats on the promotion, Aria",
        subtitle: "Celebratory · warm · the whole team",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.07 110), oklch(0.82 0.08 140))",
        pill: "New job",
        forText: "For Ben",
        sigCount: "9 signatures",
        title: "On to bigger things",
        subtitle: "Proud · excited · close colleagues",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.07 150), oklch(0.82 0.08 180))",
        pill: "New home",
        forText: "For Sam",
        sigCount: "12 signatures",
        title: "Home sweet home",
        subtitle: "Joyful · personal · friends & family",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.07 90), oklch(0.82 0.08 120))",
        pill: "Graduation",
        forText: "For Zoe",
        sigCount: "22 signatures",
        title: "Congratulations, Dr. Zoe",
        subtitle: "Proud · milestone · class of friends",
      },
    ],

    howTitle: "From one sentence to a group celebration",
    howSub:
      "A big moment deserves more than a Slack emoji. Give them a card from the whole team they'll actually remember",
    steps: [
      {
        n: "01",
        title: "Describe the achievement",
        desc: 'Tell us who it\'s for and what they did. "Aria just got promoted to Director after two years of incredible work." The AI drafts a cover and note that celebrates them properly',
      },
      {
        n: "02",
        title: "Drop the link in the group",
        desc: "Share it in the team chat, by email, or wherever makes sense. Each person signs from their own device and adds their personal note",
      },
      {
        n: "03",
        title: "Send it at the right moment",
        desc: "Deliver it on the day of the announcement, the first day in the new role, or whenever feels right. It arrives as one complete congratulations card",
      },
    ],

    usesEyebrow: "Congrats cards for every kind of win",
    usesTitle: "What are you celebrating?",
    uses: [
      {
        hue: 330,
        headline: "Congrats, Aria!",
        coverImage: "/occasions/uses/promotion-1.webp",
        title: "Promotion cards",
        desc: "From the whole team to the newly promoted. A card full of real notes beats a round of applause",
      },
      {
        hue: 18,
        headline: "Good luck, Chris",
        coverImage: "/occasions/uses/promotion-2.webp",
        title: "New job cards",
        desc: "For the colleague heading somewhere new and exciting. Everyone signs, the AI sets the tone",
      },
      {
        hue: 70,
        headline: "Welcome home, Lily",
        coverImage: "/occasions/uses/promotion-3.webp",
        title: "New home cards",
        desc: "Housewarming from the group chat. Personal, warm, something to keep on the mantle",
      },
      {
        hue: 130,
        headline: "Congrats, grad!",
        coverImage: "/occasions/uses/promotion-4.webp",
        title: "Graduation cards",
        desc: "For the degree, the doctorate, or the qualification that took years. The whole cohort signs",
      },
      {
        hue: 190,
        headline: "Welcome, baby Max",
        coverImage: "/occasions/uses/promotion-5.webp",
        title: "New baby cards",
        desc: "From the team, the friend group, or the whole extended family. Warm and celebratory",
      },
      {
        hue: 250,
        headline: "Congrats, Nadia",
        coverImage: "/occasions/uses/promotion-6.webp",
        title: "Business launch cards",
        desc: "For the founder, the freelancer, or the person who finally took the leap. Everyone sends their best",
      },
    ],

    faqEyebrow: "Congrats card FAQs",
    faqTitle: "Everything about celebrating someone",
    faqs: [
      {
        q: "How do group congratulations cards work?",
        a: "Start a card, share one link with your team or group, and everyone adds their note from their own device. The card stays private until you send it. It arrives as one complete, beautifully composed card.",
      },
      {
        q: "What occasions work well for a group congrats card?",
        a: "Any milestone worth marking: promotions, new jobs, graduations, new homes, new babies, business launches. If the group chat is buzzing about it, it's worth a card.",
      },
      {
        q: "Can I keep it a surprise?",
        a: "Yes. The card is completely private until you send it. Share the signing link with everyone except the person it's for.",
      },
      {
        q: "How quickly can I set one up?",
        a: "Under two minutes. Give the AI one sentence, and you'll have a cover, an opening note, and a signing link ready to share.",
      },
      {
        q: "Can the whole team sign without needing accounts?",
        a: "Yes. Signers just need the link. No account, no app, no download. They open it in the browser, add their note, and they're done.",
      },
      {
        q: "Is it free?",
        a: "Yes. You can design a card, collect signatures, and send it for free, and nobody who signs needs an account.",
      },
    ],

    ctaBandTitle: "What's the big news?",
    ctaBandSub:
      "Set up the card in two minutes, share the link, and let the whole team celebrate properly. We'll handle the cover, the copy, and the delivery",
  },

  kudos: {
    slug: "kudos",
    lastModified: "2026-09-29",
    label: "Kudos cards",
    shortDesc: "Recognition that's worth more than a thumbs-up",

    metaTitle: "Group Kudos Cards for Coworkers",
    metaDescription:
      "Create a group kudos card online for employee recognition and appreciation. Share one link so the whole team signs. AI drafts the cover and note. Free to start.",

    badge: "Recognition that's worth more than a thumbs-up",
    h1Line1: "Kudos cards",
    h1Muted: "that say more than",
    h1Pop: "great work",
    lede: "Start a kudos card, share one link with the team, and let everyone add a note that means something. The AI drafts a cover that names the achievement, not just the person",
    ctaText: "Start a kudos card",

    frontGradient:
      "linear-gradient(135deg, oklch(0.88 0.07 220), oklch(0.82 0.08 250))",
    cardTitle: "Well done, Taylor",
    coverImage: "/occasions/kudos.webp",
    coverHue: 40,
    sampleRecipient: "Taylor",
    sampleMessage:
      "Taylor, you shipped the big launch on time and made it look easy. Huge kudos from the whole team",
    sampleNotes: [
      {
        message: "Legendary work this quarter",
        font: "caveat",
        color: "#3f5aa8",
      },
      { message: "Rocket emoji x 100", font: "pacifico", color: "#b4452f" },
      {
        message: "Thanks for carrying us over the line. Omar",
        font: "dancing-script",
        color: "#2f7d5b",
      },
    ],

    galleryEyebrow: "Kudos card examples",
    galleryTitle: "Recognition cards that actually mean something",
    gallerySub:
      "From project wins to peer-to-peer shoutouts, these are kudos cards created with CardShare.ai: specific, sincere, and signed by the people who watched them do the work",
    gallery: [
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.07 220), oklch(0.82 0.08 250))",
        pill: "Above & beyond",
        forText: "For Taylor",
        sigCount: "8 signatures",
        title: "That launch was outstanding",
        subtitle: "Specific · peer recognition · the pod",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.06 200), oklch(0.82 0.07 230))",
        pill: "Project win",
        forText: "For the team",
        sigCount: "16 signatures",
        title: "We shipped it, together",
        subtitle: "Celebratory · team achievement · from leadership",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.06 240), oklch(0.82 0.07 270))",
        pill: "Welcome",
        forText: "For Jordan",
        sigCount: "6 signatures",
        title: "Great start, Jordan",
        subtitle: "Warm · welcoming · the whole team",
      },
      {
        gradient:
          "linear-gradient(135deg, oklch(0.88 0.06 180), oklch(0.82 0.07 210))",
        pill: "Peer kudos",
        forText: "For Alex",
        sigCount: "5 signatures",
        title: "The quiet MVP",
        subtitle: "Sincere · specific · colleagues",
      },
    ],

    howTitle: "From one sentence to meaningful recognition",
    howSub:
      'A generic "great job" wears thin fast. A card full of specific, signed notes from the people who saw it happen is the kind of recognition that sticks',
    steps: [
      {
        n: "01",
        title: "Name the achievement",
        desc: 'Tell us who it\'s for and what they did. "Taylor led the rebrand under impossible deadlines and made everyone feel calm the whole time." The AI writes something specific',
      },
      {
        n: "02",
        title: "Invite the team to add their voice",
        desc: "Share one link in Slack, email, or the team chat. Each person adds their own note. No account needed, no friction",
      },
      {
        n: "03",
        title: "Send it where it counts",
        desc: "Deliver by email or shareable link. It arrives as one complete card: specific, sincere, and signed by the people who mean it",
      },
    ],

    usesEyebrow: "Kudos cards for every kind of recognition",
    usesTitle: "What are you recognizing?",
    uses: [
      {
        hue: 18,
        headline: "Above and beyond",
        coverImage: "/occasions/uses/kudos-1.webp",
        title: "Above-and-beyond cards",
        desc: "For the person who went further than their job description asked. The team signs; the AI keeps it specific",
      },
      {
        hue: 70,
        headline: "Well done, team",
        coverImage: "/occasions/uses/kudos-2.webp",
        title: "Project completion cards",
        desc: "When the team ships something hard, a card full of notes from the whole group marks it properly",
      },
      {
        hue: 130,
        headline: "Welcome aboard, Jess",
        coverImage: "/occasions/uses/kudos-3.webp",
        title: "New employee welcome cards",
        desc: "A signed card from the whole team on day one sets the tone for everything that follows",
      },
      {
        hue: 190,
        headline: "Nice work, Ravi",
        coverImage: "/occasions/uses/kudos-4.webp",
        title: "Peer-to-peer recognition cards",
        desc: "For the colleague everyone knows does great work but rarely gets the credit. From the people who noticed",
      },
      {
        hue: 250,
        headline: "Thanks, boss",
        coverImage: "/occasions/uses/kudos-5.webp",
        title: "Manager appreciation cards",
        desc: "From the whole team to the person who's been in their corner. Specific notes carry more weight than ratings",
      },
      {
        hue: 330,
        headline: "Go team!",
        coverImage: "/occasions/uses/kudos-6.webp",
        title: "Team shoutout cards",
        desc: "For a whole squad that pulled something off. Everyone signs for everyone, recognition in every direction",
      },
    ],

    faqEyebrow: "Kudos card FAQs",
    faqTitle: "Everything about recognizing someone properly",
    faqs: [
      {
        q: "How are kudos cards different from other recognition tools?",
        a: "A kudos card is a permanent, shareable artefact, not a feed item that disappears in 24 hours. The recipient can open it any time, on any device, and see every note exactly as it was written.",
      },
      {
        q: "How do group kudos cards work?",
        a: "Start a card, share one link with the team, and everyone adds their note from their own device. The card is private until you send it. It arrives as one complete, beautifully composed card.",
      },
      {
        q: "Can signers add specific, personal notes?",
        a: "Yes. Each person writes their own note, picks their own ink color, and can add a GIF. The AI can also draft an opening message that names what was achieved.",
      },
      {
        q: "How many people can sign?",
        a: "No limit. Five colleagues or fifty. Everyone gets the same link and adds their own voice.",
      },
      {
        q: "Do signers need an account?",
        a: "No. They just need the link. They open it in the browser, add their note, and they're done.",
      },
      {
        q: "Is it free to send a kudos card?",
        a: "Yes. You can design a card, collect signatures, and send it for free, and nobody who signs needs an account.",
      },
    ],

    ctaBandTitle: "Who deserves the recognition?",
    ctaBandSub:
      "Set up the card in two minutes, share the link, and let the team say something specific. We'll handle the cover, the copy, and the delivery",
  },

  retirement: {
    slug: "retirement",
    lastModified: "2026-09-29",
    label: "Retirement cards",
    shortDesc: "A career's worth of thank yous, from everyone they worked with",

    metaTitle: "Group Retirement Cards for Coworkers",
    metaDescription:
      "Create a group retirement card online. Share one link so every colleague, past and present, signs from their own phone. AI designs the cover and drafts the note. Free to start.",

    badge: "A whole career, signed by everyone in it",
    h1Line1: "Retirement cards",
    h1Muted: "signed by a career's",
    h1Pop: "worth of colleagues",
    lede: "Start a retirement card, share one link, and let everyone from their first team to their last add a note. The AI designs a cover worthy of the occasion. You just say who's retiring",
    ctaText: "Start a retirement card",

    frontGradient:
      "linear-gradient(135deg, oklch(0.88 0.07 150), oklch(0.82 0.08 180))",
    cardTitle: "Happy Retirement, Linda",
    coverImage: "/occasions/retirement.webp",
    coverHue: 40,
    sampleRecipient: "Linda",
    sampleMessage:
      "Linda, thirty-one years, countless launches and the best advice any of us ever got. Enjoy every slow morning. With love and thanks, the whole department",
    sampleNotes: [
      {
        message: "You taught me everything. Enjoy the garden!",
        font: "caveat",
        color: "#2f7d5b",
      },
      {
        message: "The office won't be the same. Go travel!",
        font: "dancing-script",
        color: "#3f5aa8",
      },
      {
        message: "Thank you for 12 brilliant years. Raj",
        font: "pacifico",
        color: "#b4452f",
      },
    ],

    howTitle: "From one sentence to a card they'll keep for good",
    howSub:
      "Retirement cards usually miss the people who worked with them years ago. One link reaches everyone, wherever they are now",
    steps: [
      {
        n: "01",
        title: "Describe the retirement",
        desc: 'Tell us about them in a sentence e.g. "Linda retires after 31 years in finance, loves gardening and sailing." The AI drafts a cover and an opening note you can regenerate any time',
      },
      {
        n: "02",
        title: "Share one link, everyone signs",
        desc: "Send the link to the team, former colleagues and anyone they mentored. Each person adds a note from their own phone, with a GIF if they like",
      },
      {
        n: "03",
        title: "Send it on their last day",
        desc: "Present it at the send-off party, or send it by email or link on the morning they retire. It opens in the browser with every signature, and they can revisit it for years",
      },
    ],

    usesEyebrow: "Retirement cards for every send-off",
    usesTitle: "Pick the one you need",
    uses: [
      {
        hue: 150,
        headline: "Happy Retirement, Linda",
        coverImage: "/occasions/uses/retirement-1.webp",
        title: "Retirement cards for coworkers",
        desc: "The whole team, plus everyone who's moved on since, signs from one link",
      },
      {
        hue: 40,
        headline: "Enjoy it, Geoff",
        coverImage: "/occasions/uses/retirement-2.webp",
        title: "Retirement cards for your boss",
        desc: "Grateful, warm and a little bit funny. The AI keeps the tone just right",
      },
      {
        hue: 200,
        headline: "Thank you, Mrs. Patel",
        coverImage: "/occasions/uses/retirement-3.webp",
        title: "Retirement cards for teachers",
        desc: "Colleagues, parents and former students, all in one card",
      },
      {
        hue: 260,
        headline: "Happy Retirement, Dad",
        coverImage: "/occasions/uses/retirement-4.webp",
        title: "Retirement cards for family",
        desc: "For Mom, Dad or a grandparent finally putting their feet up",
      },
      {
        hue: 330,
        headline: "Thank you, Dr. Ellis",
        coverImage: "/occasions/uses/retirement-5.webp",
        title: "Retirement cards for nurses and doctors",
        desc: "From the whole ward, across every shift, without passing paper around",
      },
      {
        hue: 100,
        headline: "Here's to you, Sue",
        coverImage: "/occasions/uses/retirement-6.webp",
        title: "Funny retirement cards",
        desc: "Inside jokes, old stories and gentle teasing about the golf handicap",
      },
    ],

    faqEyebrow: "Retirement card FAQs",
    faqTitle: "Everything about sending one",
    faqs: [
      {
        q: "How do group retirement cards work?",
        a: "Start a card, share one link, and everyone adds their note from their own phone or laptop. The card stays private until you send it, then arrives as one keepsake with every message inside.",
      },
      {
        q: "Can former colleagues sign too?",
        a: "Yes. Anyone with the link can sign, so you can include people from other offices, teams they led years ago, or colleagues who have already left. There's no limit on signers.",
      },
      {
        q: "What should I write in a retirement card?",
        a: "Thank them for something specific, share a favorite memory, and wish them well for what comes next. If you're stuck, the AI can draft an opening note for the group to build on.",
      },
      {
        q: "Is CardShare.ai free?",
        a: "Yes. You can design a card, collect signatures, and send it for free, and nobody who signs needs an account.",
      },
      {
        q: "Can I start the card weeks before their last day?",
        a: "Yes. Start it as early as you like and leave the link open while people sign. Nothing is sent until you decide it's ready.",
      },
      {
        q: "Can the retiree keep the card?",
        a: "Yes. The card lives at its own link, so they can open it again any time and reread every message.",
      },
    ],

    ctaBandTitle: "Who's retiring?",
    ctaBandSub:
      "Set up the card in two minutes, share the link with everyone who worked with them, and we'll handle the cover and the delivery",
  },

  "get-well-soon": {
    slug: "get-well-soon",
    lastModified: "2026-09-29",
    label: "Get well soon cards",
    shortDesc: "Let them know the whole team is thinking of them",

    metaTitle: "Group Get Well Soon Cards Online",
    metaDescription:
      "Send a group get well soon card online. Share one link so coworkers, friends and family all sign from their own phone. AI designs the cover and drafts the note. Free to start.",

    badge: "Everyone's thinking of them, in one card",
    h1Line1: "Get well soon cards",
    h1Muted: "from everyone,",
    h1Pop: "right when it matters",
    lede: "Start a get well card, share one link, and let everyone add a warm note from wherever they are. It arrives as one card they can open from a hospital bed or the sofa. No stamps, no delays",
    ctaText: "Start a get well card",

    frontGradient:
      "linear-gradient(135deg, oklch(0.9 0.07 90), oklch(0.85 0.08 120))",
    cardTitle: "Get well soon, Ben",
    coverImage: "/occasions/get-well-soon.webp",
    coverHue: 280,
    sampleRecipient: "Ben",
    sampleMessage:
      "Ben, we're all rooting for you. Rest up, take all the time you need, and don't even think about your inbox. Love, the team",
    sampleNotes: [
      {
        message: "Thinking of you. The desk plant is thriving!",
        font: "caveat",
        color: "#2f7d5b",
      },
      {
        message: "Feel better soon, we miss you",
        font: "dancing-script",
        color: "#3f5aa8",
      },
      {
        message: "Sending soup vibes. Ana x",
        font: "pacifico",
        color: "#b4452f",
      },
    ],

    howTitle: "A card that reaches them today, not next week",
    howSub:
      "When someone's unwell, speed matters more than stationery. One link, everyone signs, and it's with them the same day",
    steps: [
      {
        n: "01",
        title: "Say who it's for",
        desc: 'Describe them in a sentence e.g. "Ben is recovering from knee surgery and loves football." The AI drafts a cheerful cover and a gentle opening note',
      },
      {
        n: "02",
        title: "Share one link, everyone signs",
        desc: "Drop the link in the team channel or family chat. Each person adds a note and a GIF from their own phone. No account needed",
      },
      {
        n: "03",
        title: "Send it straight away",
        desc: "Send it by email or text as soon as it's full. It opens in any browser, so it works just as well on a phone in a hospital ward",
      },
    ],

    usesEyebrow: "Get well cards for everyone",
    usesTitle: "Pick the one you need",
    uses: [
      {
        hue: 90,
        headline: "Get well soon, Ben",
        coverImage: "/occasions/uses/get-well-soon-1.webp",
        title: "Get well cards for coworkers",
        desc: "The whole team signs from one link, even the people working remotely",
      },
      {
        hue: 160,
        headline: "Speedy recovery, Jo",
        coverImage: "/occasions/uses/get-well-soon-2.webp",
        title: "After surgery",
        desc: "Something cheerful to open while they rest and recover",
      },
      {
        hue: 220,
        headline: "Thinking of you, Kim",
        coverImage: "/occasions/uses/get-well-soon-3.webp",
        title: "Thinking of you cards",
        desc: "For longer illnesses, when a gentle note means more than a jokey one",
      },
      {
        hue: 30,
        headline: "Feel better, Grandma",
        coverImage: "/occasions/uses/get-well-soon-4.webp",
        title: "Get well cards for family",
        desc: "Every cousin, aunt and grandchild in one card, wherever they live",
      },
      {
        hue: 300,
        headline: "Get well soon, Leo",
        coverImage: "/occasions/get-well-soon.webp",
        title: "Get well cards for kids",
        desc: "Bright covers and GIFs from classmates to brighten a sick day",
      },
      {
        hue: 250,
        headline: "Rest up, Mia",
        coverImage: "/occasions/uses/get-well-soon-5.webp",
        title: "Get well cards for friends",
        desc: "The whole group chat, in one card that actually arrives",
      },
    ],

    faqEyebrow: "Get well card FAQs",
    faqTitle: "Everything about sending one",
    faqs: [
      {
        q: "How do group get well soon cards work?",
        a: "Start a card, share one link, and everyone adds their note from their own phone or laptop. When it's ready, send it by email or a link they can open anywhere.",
      },
      {
        q: "Can they open the card in hospital?",
        a: "Yes. The card opens in any web browser, so they can read it on their phone or a tablet. There's nothing to download or install.",
      },
      {
        q: "What should I write in a get well card?",
        a: "Keep it warm and simple: let them know you're thinking of them, take the pressure off work, and add a small bit of news or a joke if it fits. The AI can draft an opening note for the group.",
      },
      {
        q: "Does everyone who signs need an account?",
        a: "No. Signers just need the link. They open it in the browser, add a note, and they're done.",
      },
      {
        q: "Is CardShare.ai free?",
        a: "Yes. You can design a card, collect signatures, and send it for free, and nobody who signs needs an account.",
      },
    ],

    ctaBandTitle: "Who could use some cheering up?",
    ctaBandSub:
      "Set up the card in two minutes, share the link, and let everyone send their best. It can be with them today",
  },

  sympathy: {
    slug: "sympathy",
    lastModified: "2026-09-29",
    label: "Sympathy cards",
    shortDesc: "Gentle words from everyone, when they matter most",

    metaTitle: "Group Sympathy & Condolence Cards",
    metaDescription:
      "Send a group sympathy card online. Share one link so colleagues and friends can each write a condolence message. A calm, respectful card with every note in one place. Free to start.",

    badge: "Support from everyone, gathered with care",
    h1Line1: "Sympathy cards",
    h1Muted: "with kind words",
    h1Pop: "from everyone",
    lede: "Start a condolence card, share one link, and let colleagues and friends each write a few kind words. It arrives as one calm, respectful card they can read when they're ready",
    ctaText: "Start a sympathy card",

    frontGradient:
      "linear-gradient(135deg, oklch(0.9 0.03 240), oklch(0.85 0.04 270))",
    cardTitle: "With deepest sympathy",
    coverImage: "/occasions/sympathy.webp",
    coverHue: 200,
    sampleRecipient: "Hannah",
    sampleMessage:
      "Hannah, we're so sorry for your loss. Please take all the time you need. We're thinking of you and your family, and we're here whenever you need us",
    sampleNotes: [
      {
        message: "Holding you in my thoughts. Anything you need",
        font: "caveat",
        color: "#3f5aa8",
      },
      {
        message: "So sorry, Hannah. Sending love",
        font: "dancing-script",
        color: "#5b4a8a",
      },
      {
        message: "Thinking of you all. Tom",
        font: "caveat",
        color: "#2f7d5b",
      },
    ],

    howTitle: "A thoughtful card, without the logistics",
    howSub:
      "Nobody wants to chase signatures at a time like this. One link lets everyone say something kind, in their own words",
    steps: [
      {
        n: "01",
        title: "Set the tone",
        desc: "Tell us who it's for in a sentence. The AI suggests a calm, understated cover and a short opening note, and you can change either until it feels right",
      },
      {
        n: "02",
        title: "Share one link, everyone writes",
        desc: "Send the link to colleagues or friends. Each person writes a note privately from their own phone. Nothing is shared until you send it",
      },
      {
        n: "03",
        title: "Send it when it's ready",
        desc: "Send it by email or a private link. They can open it whenever they feel ready, and come back to it any time",
      },
    ],

    usesEyebrow: "Sympathy cards for every situation",
    usesTitle: "Pick the one you need",
    uses: [
      {
        hue: 240,
        headline: "With deepest sympathy",
        coverImage: "/occasions/uses/sympathy-1.webp",
        title: "Sympathy cards for coworkers",
        desc: "Let a colleague know the whole team is thinking of them",
      },
      {
        hue: 200,
        headline: "Thinking of you",
        coverImage: "/occasions/uses/sympathy-2.webp",
        title: "Condolence cards for friends",
        desc: "Kind words from the whole group, gathered in one place",
      },
      {
        hue: 280,
        headline: "In loving memory",
        coverImage: "/occasions/uses/sympathy-3.webp",
        title: "Memorial cards",
        desc: "Memories from everyone who knew them, kept together",
      },
      {
        hue: 150,
        headline: "So sorry, Jess",
        coverImage: "/occasions/uses/sympathy-4.webp",
        title: "Pet sympathy cards",
        desc: "Losing a pet is losing family. A gentle note from everyone who knew them",
      },
      {
        hue: 60,
        headline: "With love and support",
        coverImage: "/occasions/uses/sympathy-5.webp",
        title: "Sympathy cards for family",
        desc: "Every relative's message in one card, however far apart you are",
      },
      {
        hue: 320,
        headline: "We're here for you",
        coverImage: "/occasions/uses/sympathy-6.webp",
        title: "Thinking of you cards",
        desc: "For hard times of any kind, when you want them to know they're not alone",
      },
    ],

    faqEyebrow: "Sympathy card FAQs",
    faqTitle: "Everything about sending one",
    faqs: [
      {
        q: "How do group sympathy cards work?",
        a: "Start a card, share one link, and everyone writes their own note from their phone or laptop. The card stays private until you send it, then arrives as one card with every message inside.",
      },
      {
        q: "What should I write in a sympathy card?",
        a: "Keep it short and sincere. Say you're sorry for their loss, share a kind memory if you have one, and let them know you're there. There's no need to find perfect words.",
      },
      {
        q: "Can I keep the tone calm and respectful?",
        a: "Yes. You choose the cover and the opening note, and can regenerate or edit either until the tone feels right. You can also leave out GIFs and bright colors entirely.",
      },
      {
        q: "Can people share a memory?",
        a: "Yes. Each person writes their own note, so the card becomes a lasting collection of memories from everyone who took part.",
      },
      {
        q: "Is CardShare.ai free?",
        a: "Yes. You can design a card, collect messages, and send it for free, and nobody who writes in it needs an account.",
      },
    ],

    ctaBandTitle: "Let them know they're not alone",
    ctaBandSub:
      "Set up the card in a couple of minutes, share the link, and let everyone say something kind. We'll take care of the rest",
  },

  "new-baby": {
    slug: "new-baby",
    lastModified: "2026-09-29",
    label: "New baby cards",
    shortDesc: "Congratulations from everyone, for the newest arrival",

    metaTitle: "Group New Baby & Baby Shower Cards",
    metaDescription:
      "Create a group new baby card online. Share one link so coworkers, friends and family sign from their own phone, perfect for baby showers and parental leave. Free to start.",

    badge: "The newest arrival deserves a full card",
    h1Line1: "New baby cards",
    h1Muted: "signed by everyone,",
    h1Pop: "kept forever",
    lede: "Start a new baby card, share one link, and let everyone add their congratulations from their own phone. The AI designs the cover. Perfect for baby showers and colleagues heading off on parental leave",
    ctaText: "Start a new baby card",

    frontGradient:
      "linear-gradient(135deg, oklch(0.9 0.06 200), oklch(0.88 0.06 340))",
    cardTitle: "Welcome, baby Noah",
    coverImage: "/occasions/new-baby.webp",
    coverHue: 60,
    sampleRecipient: "Priya and Sam",
    sampleMessage:
      "Priya and Sam, congratulations on the arrival of little Noah! Wishing you sleep, joy and all the tiny socks you could need. Love, the whole team",
    sampleNotes: [
      {
        message: "So happy for you both! Can't wait to meet him",
        font: "caveat",
        color: "#3f5aa8",
      },
      {
        message: "Welcome to the world, Noah!",
        font: "pacifico",
        color: "#b4452f",
      },
      {
        message: "Enjoy every moment. Mel x",
        font: "dancing-script",
        color: "#2f7d5b",
      },
    ],

    howTitle: "From one sentence to a signed card in minutes",
    howSub:
      "New parents don't have time to open a stack of envelopes. One card, every message, ready whenever there's a quiet moment",
    steps: [
      {
        n: "01",
        title: "Tell us the happy news",
        desc: 'Describe it in a sentence e.g. "Priya and Sam just welcomed baby Noah." The AI drafts a cover and an opening note you can regenerate any time',
      },
      {
        n: "02",
        title: "Share one link, everyone signs",
        desc: "Share it in the team channel or the family chat. Everyone adds a note, and a GIF if they like, from their own phone",
      },
      {
        n: "03",
        title: "Send it when it's full",
        desc: "Send it by email or a link, or share it at the baby shower. The parents can open it whenever they get a moment",
      },
    ],

    usesEyebrow: "Baby cards for every occasion",
    usesTitle: "Pick the one you need",
    uses: [
      {
        hue: 200,
        headline: "Welcome, baby Noah",
        coverImage: "/occasions/uses/new-baby-1.webp",
        title: "New baby cards for coworkers",
        desc: "The whole team signs before they head off on parental leave",
      },
      {
        hue: 340,
        headline: "Oh baby!",
        coverImage: "/occasions/uses/new-baby-2.webp",
        title: "Baby shower cards",
        desc: "Collect notes from every guest, including the ones who can't make it",
      },
      {
        hue: 120,
        headline: "Congrats, Mo and Ali",
        coverImage: "/occasions/uses/new-baby-3.webp",
        title: "Cards for new parents",
        desc: "Congratulations and good-luck-sleeping wishes from everyone",
      },
      {
        hue: 60,
        headline: "Welcome home, Ivy",
        coverImage: "/occasions/uses/new-baby-4.webp",
        title: "Adoption cards",
        desc: "Celebrate a new family with messages from everyone who loves them",
      },
      {
        hue: 270,
        headline: "Double trouble!",
        coverImage: "/occasions/uses/new-baby-5.webp",
        title: "Twins cards",
        desc: "Twice the congratulations, all in one card",
      },
      {
        hue: 20,
        headline: "Hello, little one",
        coverImage: "/occasions/uses/new-baby-6.webp",
        title: "Grandparent cards",
        desc: "For new grandparents, from the whole extended family",
      },
    ],

    faqEyebrow: "New baby card FAQs",
    faqTitle: "Everything about sending one",
    faqs: [
      {
        q: "How do group new baby cards work?",
        a: "Start a card, share one link, and everyone adds their note from their own phone or laptop. When it's ready, send it by email or a link the new parents can open any time.",
      },
      {
        q: "Can I use it for a baby shower?",
        a: "Yes. Share the link before the shower so guests who can't attend can still sign, then send or present the card on the day.",
      },
      {
        q: "What should I write in a new baby card?",
        a: "Congratulate them, welcome the baby by name, and add a warm wish or a light joke about sleep. The AI can draft an opening note for the group.",
      },
      {
        q: "Can people add GIFs?",
        a: "Yes. Each signer can add a GIF alongside their note, picked from a built-in search.",
      },
      {
        q: "Is CardShare.ai free?",
        a: "Yes. You can design a card, collect signatures, and send it for free, and nobody who signs needs an account.",
      },
    ],

    ctaBandTitle: "Who's welcoming a little one?",
    ctaBandSub:
      "Set up the card in two minutes, share the link, and let everyone send their congratulations. We'll handle the cover and the delivery",
  },

  graduation: {
    slug: "graduation",
    lastModified: "2026-09-29",
    label: "Graduation cards",
    shortDesc: "Big congratulations from everyone who cheered them on",

    metaTitle: "Group Graduation Cards Online",
    metaDescription:
      "Create a group graduation card online. Share one link so family, friends and teachers all sign from their own phone. AI designs the cover and drafts the note. Free to start.",

    badge: "They did it. Everyone should say so",
    h1Line1: "Graduation cards",
    h1Muted: "signed by everyone",
    h1Pop: "who cheered them on",
    lede: "Start a graduation card, share one link, and let family, friends and teachers add their congratulations. The AI designs a cover that celebrates the achievement. You just say who's graduating",
    ctaText: "Start a graduation card",

    frontGradient:
      "linear-gradient(135deg, oklch(0.88 0.08 260), oklch(0.84 0.09 290))",
    cardTitle: "Congrats, Grad!",
    coverImage: "/occasions/graduation.webp",
    coverHue: 70,
    sampleRecipient: "Maya",
    sampleMessage:
      "Maya, you did it! All those late nights paid off. We're so proud of you and can't wait to see what's next. Love, everyone",
    sampleNotes: [
      {
        message: "So proud of you! Onwards and upwards",
        font: "caveat",
        color: "#3f5aa8",
      },
      {
        message: "Congratulations, graduate!",
        font: "pacifico",
        color: "#b4452f",
      },
      {
        message: "The world's not ready. Uncle Dev",
        font: "dancing-script",
        color: "#2f7d5b",
      },
    ],

    howTitle: "From one sentence to a signed card in minutes",
    howSub:
      "Family across the country, friends across campus, teachers from years ago. One link reaches all of them",
    steps: [
      {
        n: "01",
        title: "Describe the achievement",
        desc: 'Tell us about it in a sentence e.g. "Maya graduates in biology and is off to vet school." The AI drafts a cover and an opening note you can regenerate any time',
      },
      {
        n: "02",
        title: "Share one link, everyone signs",
        desc: "Share it in the family chat or with their friends. Everyone adds a note, and a GIF if they like, from their own phone",
      },
      {
        n: "03",
        title: "Send it on graduation day",
        desc: "Send it on the morning of the ceremony, or the moment it's full. It opens in any browser, with every note included",
      },
    ],

    usesEyebrow: "Graduation cards for every milestone",
    usesTitle: "Pick the one you need",
    uses: [
      {
        hue: 260,
        headline: "Congrats, Grad!",
        coverImage: "/occasions/uses/graduation-1.webp",
        title: "College graduation cards",
        desc: "Family, friends and roommates in one card for the big day",
      },
      {
        hue: 30,
        headline: "Well done, Jake",
        coverImage: "/occasions/uses/graduation-2.webp",
        title: "High school graduation cards",
        desc: "From the whole family and the teachers who got them there",
      },
      {
        hue: 180,
        headline: "Dr. Chen!",
        coverImage: "/occasions/uses/graduation-3.webp",
        title: "PhD and masters cards",
        desc: "Years of work deserve a card from the whole lab and everyone who helped",
      },
      {
        hue: 330,
        headline: "Look at you go!",
        coverImage: "/occasions/uses/graduation-4.webp",
        title: "Kindergarten graduation cards",
        desc: "A bright, fun card from classmates, parents and teachers",
      },
      {
        hue: 100,
        headline: "Qualified!",
        coverImage: "/occasions/uses/graduation-5.webp",
        title: "Cards for coworkers who graduate",
        desc: "For colleagues finishing a degree or qualification while working",
      },
      {
        hue: 220,
        headline: "Class of 2027",
        coverImage: "/occasions/uses/graduation-6.webp",
        title: "Cards from the whole class",
        desc: "Classmates sign each other's cards, all from one link",
      },
    ],

    faqEyebrow: "Graduation card FAQs",
    faqTitle: "Everything about sending one",
    faqs: [
      {
        q: "How do group graduation cards work?",
        a: "Start a card, share one link, and everyone adds their note from their own phone or laptop. When it's ready, send it by email or a link they can open anywhere.",
      },
      {
        q: "Can family who live far away sign?",
        a: "Yes. Anyone with the link can sign from anywhere, so relatives and friends in other cities or countries can all be part of the card.",
      },
      {
        q: "What should I write in a graduation card?",
        a: "Congratulate them on the achievement, mention something specific about their hard work, and wish them luck with what comes next. The AI can draft an opening note for the group.",
      },
      {
        q: "Can I start the card before graduation day?",
        a: "Yes. Start it as early as you like and leave the link open while people sign. Nothing is sent until you decide it's ready.",
      },
      {
        q: "Is CardShare.ai free?",
        a: "Yes. You can design a card, collect signatures, and send it for free, and nobody who signs needs an account.",
      },
    ],

    ctaBandTitle: "Who's graduating?",
    ctaBandSub:
      "Set up the card in two minutes, share the link, and let everyone who cheered them on sign. We'll handle the rest",
  },

  holiday: {
    slug: "holiday",
    lastModified: "2026-09-29",
    label: "Holiday cards",
    shortDesc: "Season's greetings from the whole team, in one card",

    metaTitle: "Group Holiday & Christmas Cards for Teams",
    metaDescription:
      "Create a group holiday card online. Share one link so the whole team signs a Christmas or season's greetings card for clients, colleagues or a manager. Free to start.",

    badge: "Season's greetings, signed by the whole team",
    h1Line1: "Holiday cards",
    h1Muted: "the whole team signs,",
    h1Pop: "sent in minutes",
    lede: "Start a holiday card, share one link, and let everyone add their season's greetings from their own phone. The AI designs a festive cover. Perfect for clients, remote teams and the office party",
    ctaText: "Start a holiday card",

    frontGradient:
      "linear-gradient(135deg, oklch(0.86 0.08 150), oklch(0.82 0.1 25))",
    cardTitle: "Happy Holidays",
    coverImage: "/occasions/holiday.webp",
    coverHue: 250,
    sampleRecipient: "the Northwind team",
    sampleMessage:
      "Thank you for a brilliant year of working together. Wishing you a restful break and a happy new year. From all of us",
    sampleNotes: [
      {
        message: "Happy holidays! See you in January",
        font: "caveat",
        color: "#b4452f",
      },
      {
        message: "Thanks for a great year together",
        font: "dancing-script",
        color: "#2f7d5b",
      },
      {
        message: "Enjoy the break! Lou",
        font: "pacifico",
        color: "#3f5aa8",
      },
    ],

    howTitle: "One card from the whole team, before the break",
    howSub:
      "December is busy enough. Skip passing a card around the office and let everyone sign from their own phone",
    steps: [
      {
        n: "01",
        title: "Describe the card",
        desc: 'Tell us who it\'s for in a sentence e.g. "A thank-you holiday card from our team to the Northwind account." The AI drafts a festive cover and opening note',
      },
      {
        n: "02",
        title: "Share one link, everyone signs",
        desc: "Share it in Slack or email. Everyone adds a note, and a GIF if they like, including remote and part-time colleagues",
      },
      {
        n: "03",
        title: "Send it before the break",
        desc: "Send it by email or link as soon as everyone has signed. It opens in any browser, with every note included",
      },
    ],

    usesEyebrow: "Holiday cards for every audience",
    usesTitle: "Pick the one you need",
    uses: [
      {
        hue: 150,
        headline: "Happy Holidays",
        coverImage: "/occasions/uses/holiday-1.webp",
        title: "Holiday cards for clients",
        desc: "A warm thank-you from everyone who works with them",
      },
      {
        hue: 25,
        headline: "Merry Christmas, Ellie",
        coverImage: "/occasions/uses/holiday-2.webp",
        title: "Christmas cards for your boss",
        desc: "The whole team in one card, no awkward office envelope",
      },
      {
        hue: 220,
        headline: "Season's greetings",
        coverImage: "/occasions/uses/holiday-3.webp",
        title: "Cards for remote teams",
        desc: "Everyone signs from wherever they are, across every time zone",
      },
      {
        hue: 60,
        headline: "Happy New Year!",
        coverImage: "/occasions/uses/holiday-4.webp",
        title: "New Year cards",
        desc: "Round off the year with notes from the whole team",
      },
      {
        hue: 280,
        headline: "Happy Hanukkah",
        coverImage: "/occasions/uses/holiday-5.webp",
        title: "Hanukkah cards",
        desc: "Eight nights of good wishes, gathered in one card",
      },
      {
        hue: 330,
        headline: "Merry Christmas, Grandma",
        coverImage: "/occasions/uses/holiday-6.webp",
        title: "Christmas cards for family",
        desc: "Every relative signs, near or far, in one festive card",
      },
    ],

    faqEyebrow: "Holiday card FAQs",
    faqTitle: "Everything about sending one",
    faqs: [
      {
        q: "How do group holiday cards work?",
        a: "Start a card, share one link, and everyone adds their note from their own phone or laptop. When it's ready, send it by email or a link they can open anywhere.",
      },
      {
        q: "Can I send a holiday card to a client from the whole team?",
        a: "Yes. Share the link internally so everyone who works with the client can sign, then send the finished card to your contact by email.",
      },
      {
        q: "Is it only for Christmas?",
        a: "No. You can make a card for any holiday, including Hanukkah, Diwali, Lunar New Year or New Year, or keep it neutral with season's greetings.",
      },
      {
        q: "Can remote colleagues sign too?",
        a: "Yes. Anyone with the link can sign from any device, in any time zone, so the whole team can be in the card.",
      },
      {
        q: "Is CardShare.ai free?",
        a: "Yes. You can design a card, collect signatures, and send it for free, and nobody who signs needs an account.",
      },
    ],

    ctaBandTitle: "Who's on your holiday list?",
    ctaBandSub:
      "Set up the card in two minutes, share the link with the team, and send season's greetings from everyone at once",
  },
}

export const ALL_CATEGORY_SLUGS = Object.keys(CATEGORY_CONFIGS)

export const BROWSE_CATEGORY_SLUGS = [
  "birthday",
  "work-anniversary",
  "wedding",
  "promotion",
  "thank-you",
  "farewell",
  "kudos",
  "retirement",
  "get-well-soon",
  "sympathy",
  "new-baby",
  "graduation",
  "holiday",
] as const

export function getBrowseCategories(): CategoryConfig[] {
  return BROWSE_CATEGORY_SLUGS.map((slug) => CATEGORY_CONFIGS[slug])
}

/** The browse occasions as tiles for `CardTileRow` (browse page and homepage). */
export function occasionTiles() {
  return getBrowseCategories().map((cat) => ({
    key: cat.slug,
    href: `/browse/${cat.slug}`,
    background: cat.frontGradient,
    coverImage: cat.coverImage,
    coverHue: cat.coverHue,
    headline: cat.cardTitle,
    title: cat.label,
    desc: cat.shortDesc,
  }))
}

export function getCategoryConfig(slug: string): CategoryConfig | undefined {
  return CATEGORY_CONFIGS[slug]
}
