-- Legacy helper script (kept for historical reference).
-- Public contribution UPDATE has been removed; owners-only RLS is enforced in
-- migrations and trusted route handlers use service-role credentials.
